### ISSUE TITLE
How to define object and values?

### ISSUE THREAD

**Issue by alimtolman** [microsoft/ClearScript#120]
Hello.
So, it's strange question. The full question is "how define object that are not existing in the program memory" `AddHostType` method is not that I need.
I've tried to assign value to the `Script` but it's also doesn't work.
What I need?
I need it to work:
```
var engine = new V8ScriptEngine();

engine.Script["a"] = new object();
engine.Script["a.b"] = 1;

engine.Execute("var c= a.b;");

Console.WriteLine(engine.Script["c"]);
```

And also another question.
If I'll execute some code several time with one engine the document name is changing to `Script name [i]` where `i - count of the executed count`.
How to prevent it?

**Comment by alimtolman** [comment]
For the first question I've found solution.
```
var engine = new V8ScriptEngine();

engine.Script["a"] = new ExpandoObject();
engine.Script["a"].b = 1;

engine.Execute("var c = a.b;");

Console.WriteLine(engine.Script["c"]);
```
Second question is still actual.

**Comment by ClearScriptLib** [comment]
Hi @alimtolman,

A couple of points about your first question:

- If you're looking for a simple dynamic "bag of properties" object, `ExpandoObject` is one of several possibilities. You could also use ClearScript's [`PropertyBag`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_PropertyBag.htm), or even a native JavaScript object: `engine.Script["a"] = engine.Evaluate("({})");`. The latter is best for objects expected to be accessed primarily from script code.

- The indexing syntax is unnecessary; you can simply do this: `engine.Script.a = new PropertyBag();`.

Regarding your second question:

- Unique script names are necessary to ensure that _different_ scripts are all accessible in debuggers.
- How are these names affecting you? That is, where are you seeing them?
- If you specify a [`Uri`](https://docs.microsoft.com/en-us/dotnet/api/system.uri), ClearScript will use it instead of the script name, without modification:

``` C#
var uri = new Uri("MyScript", UriKind.RelativeOrAbsolute);
engine.Execute(new DocumentInfo(uri), "var c = a.b;");
```

- Of course, if you use the same `Uri` for different scripts, all but one may be inaccessible in debuggers.
- In general, try to avoid re-parsing the same JavaScript source code more than once. Consider using a [compiled script](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_V8_V8ScriptEngine_Compile.htm) or invoking a script function defined earlier.

Good luck!
