### ISSUE TITLE
Setting and setting values using host's overloaded indexer 

### ISSUE THREAD

**Issue by jonghshin** [microsoft/ClearScript#132]
Hello,
Thank you very much for building this wonderful program.
ClearScript made possible for our application to use V8 engine, and we are very very grateful!

But there is one thing that ClearScript is missing.
We cannot get or set value from/to the host's overloaded indexer.
Let's say we have a class that overloads an indexer like this.

public class IndexerTest
    {
        private Dictionary<string, object> dictionary = new Dictionary<string, object>()
        {
            { "CurrentTime", DateTime.Now },
            { "Greeting", "Hello" },
        };
        public object Get(string name)
        {
            return dictionary[name];
        }
        public void Set(string name, object value)
        {
            dictionary[name] = value;
        }
        // Indexer overloading
        public object this[string name]
        {
            get
            {
                return Get(name);
            }
            set
            {
                Set(name, value);
            }
        }
    }

And if we execute the following script with a instance of the class above like this,

using (var engine = new V8ScriptEngine())
{
   IndexerTest indexerTest = new IndexerTest();
   engine.AddHostObject("Container", indexerTest);
   engine.Execute("Container.Set(\"Greeting\", \"guten Morgen\")"); // Successful
   engine.Execute("Container[\"Greeting\"] = \"guten Morgen\"");  // Unsuccessful
}

the Set method is called and set value successfully, but we get this error message when trying to set value through the indexer.

Error: Object has no suitable property or field named 'Greeting'

If we can set and get values through indexer, it would be very very helpful.

Thank you!

**Comment by ClearScriptLib** [comment]
Hi @jonghshin,

Thanks for your kind words!

The problem here is that C# and JavaScript indexing are fundamentally different facilities.

Some background: Indexers are actually _indexed properties_ under the hood - special properties with extra parameters. Like all properties, they have names (usually "Item"), but those names are hidden under the cover of C#'s bracket syntax.

A .NET object and its indexer can expose completely different property sets (and usually do), not to mention that indexers can be overloaded, have multiple parameters, etc.

None of this applies to JavaScript, where `foo["bar"]` is equivalent to `foo.bar`, period. In fact, if `foo` is a .NET object, ClearScript's property access hook can't discover which JavaScript syntax is invoking it.

This creates ambiguity that ClearScript can't resolve. Using your test class as an example, when JavaScript code attempts to access a property named "Set", ClearScript has no way to guess whether it's trying to access the `Set` method or pass "Set" to the indexer.

Still, ClearScript aims to provide full access to .NET objects, so it does support indexers, but it does so through a syntax that, by necessity, is rather clumsy. In your case it looks like this:

``` JavaScript
// JavaScript
value = Container.Item.get(name); // or Container.Item(name)
Container.Item.set(name, value);
```

This syntax is flexible enough to support overloaded indexers, indexers with multiple parameters, etc. Unfortunately, while it provides full access, it's probably not what you're looking for.

There are many ways to expose .NET objects such that they appear more JavaScript-like. For example:
- ClearScript supports dynamic projection for objects that implement [`IList`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist), [`IPropertyBag`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_IPropertyBag.htm), or [`IDynamicMetaObjectProvider`](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.idynamicmetaobjectprovider).
- You could wrap a property bag around your object and populate it with forwarding delegates that invoke the object's methods.
- You could use a custom dynamic wrapper.
- You could use a [JavaScript proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) wrapper.

Each approach has strengths and weaknesses, and there are other possibilities. Let us know if you're interested in a specific example.

Good luck!

**Comment by jonghshin** [comment]
it would be greatly appreciated if you could provide some examples.

Thank you!

**Comment by ClearScriptLib** [comment]
Hi @jonghshin,

It's great to hear that you found a solution that works for you. `ExpandoObject` implements `IDynamicMetaObjectProvider`, an interface that triggers dynamic projection automatically.

It's possible to expose a custom indexer the way you originally planned, but it would be a bit more work.

Cheers!

**Comment by sallenorigami** [comment]
Can I get some examples that cover IDynamicMetaObjectProvider, and the Javascript Proxy?

**Comment by ClearScriptLib** [comment]
Hi @sallenorigami,

[`IDynamicMetaObjectProvider`](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.idynamicmetaobjectprovider) and [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) are generic facilities that serve many purposes. If you could give us an idea of your requirements, we'd be happy to provide relevant examples.

Thanks!

**Comment by sallenorigami** [comment]
My requirements are almost identical to the original requirement of this thread, but I can not use ExpandoObject, as it is not extensible.

**Comment by Hermes1312** [comment]
Dynamic ExpandoObject as Dictionary works perfect.

Code:
```
var dictionary = new ExpandoObject() as IDictionary<string, object>; 

using var engine = new V8ScriptEngine();
engine.AddHostObject("dictionary", dictionary);
engine.AddHostObject("log", new Action<object>(Console.WriteLine));
engine.Execute(@"
    dictionary['someKey'] = 1312;
    dictionary.anotherKey = 2131;

    log(dictionary['someKey']);
    log(dictionary['anotherKey']);
    log(dictionary.anotherKey);
    log(dictionary.someKey);
");
```

Output:
```
1312
2131
2131
1312
```
