### ISSUE TITLE
Simplify module injection

### ISSUE THREAD

**Issue by Taritsyn** [microsoft/ClearScript#143]
Suppose we have the following code:

```csharp
using System;

using Microsoft.ClearScript;
using Microsoft.ClearScript.JavaScript;
using Microsoft.ClearScript.V8;

namespace TestClearScriptModules
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var engine = new V8ScriptEngine())
            {
                object result = engine.Evaluate(
                    new DocumentInfo { Category = ModuleCategory.Standard },
                    @"let notExported = 'abc';
export function square(x) {
    return x * x;
}
export const MY_CONSTANT = 123;"
                );

                Console.WriteLine("result = {0}", result);
            }
        }
    }
}
```

This module exports function and constant. How can I get the values of these exports without modifying JS code?

**Comment by ClearScriptLib** [comment]
Hi Andrey,

The only way to access a standard module's exports is to [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) them, and since importing is entangled with loading, there's really no need to `Execute` or `Evaluate` any module except possibly the top-level one. Instead, you simply issue an `import` statement, and the corresponding module is automatically loaded if necessary.

Now, ClearScript's default loader can read modules from the file system or download them from the web, but if you need the ability to inject module code directly, you can easily provide a custom loader that does the job. Here's an example:

``` C#
internal class MyLoader : DocumentLoader {
    private readonly Dictionary<string, Document> preloads = new Dictionary<string, Document>();
    public void AddPreload(string name, DocumentCategory category, string code) {
        var document = new StringDocument(new DocumentInfo(name) { Category = category }, code);
        preloads.Add(name, document);
    }
    public override async Task<Document> LoadDocumentAsync(DocumentSettings settings, DocumentInfo? sourceInfo, string specifier, DocumentCategory category, DocumentContextCallback contextCallback) {
        Document preload;
        if (preloads.TryGetValue(specifier, out preload)) {
            return preload;
        }
        return await Default.LoadDocumentAsync(settings, sourceInfo, specifier, category, contextCallback);
    }
}
```

Now, instead of using `Evaluate`, you can inject your module's code as follows:

``` C#
var myLoader = new MyLoader();
engine.DocumentSettings.Loader = myLoader;
myLoader.AddPreload("myModule", ModuleCategory.Standard, @"
    let notExported = 'abc';
    export function square(x) {
        return x * x;
    }
    export const MY_CONSTANT = 123;
");
```

And now other modules can simply `import ... from 'myModule'`. If you need to access module exports from the host, you can easily do that too:

``` C#
dynamic myExports = engine.Evaluate(new DocumentInfo {Category = ModuleCategory.Standard}, @"
    import * as myExports from 'myModule';
    myExports;
");
Console.WriteLine("{0} {1}", myExports.square(8), myExports.MY_CONSTANT);
```

We might add a similar "preload-capable" loader to ClearScript in the future, but for now you'll have to use a custom one.

Good luck!

**Comment by Taritsyn** [comment]
Thanks for information!

> We might add a similar "preload-capable" loader to ClearScript in the future, …

It would be great.

**Comment by ClearScriptLib** [comment]
[ClearScript 6.0](https://github.com/microsoft/ClearScript/releases/tag/6.0.0) added support for [system documents](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_DocumentSettings_AddSystemDocument.htm) to resolve this issue.
