### ISSUE TITLE
Can't Invoke const function variable

### ISSUE THREAD

**Issue by kristianoye** [microsoft/ClearScript#149]
I declared an external JavaScript function as:

```
const performCalculation = (a) => {
...
};

```

But when I try to Invoke the method from C#, ClearScript throws an exception:

"TypeError: Method or property not found" (declaring this same variable as a var works).  Evaluating this as a 'const' in Chrome's debugging window works as expected.

**Comment by ClearScriptLib** [comment]
Hi @kristianoye,

The behavior you're seeing is correct.

Unlike `var`, the `let` and `const` statements do _not_ create global object properties. Not being reachable from the global object, JavaScript constants and `let` variables are inaccessible to the host.

They are, of course, accessible to script code, so `engine.Evaluate("performCalculation(123)")` should work. However, as each such invocation incurs the overhead of parsing and compiling a new script document, this approach is generally inadvisable.

Instead of `const`, consider creating a read-only global object property:

``` C#
engine.Execute(@"
    Object.defineProperty(this, 'performCalculation', {
        value: function (a) {
            ...
        }
    });
");
var result = engine.Script.performCalculation(123);
```

You could also return the constant to the host:

``` C#
dynamic performCalculation = engine.Evaluate(@"
    const performCalculation = (a) => {
        ...
    };
    performCalculation
");
var result = performCalculation(123);
```

Good luck!

**Comment by kristianoye** [comment]
Ahh, interesting.  I just figured they would be accessible since I defined them in what I thought was the global space.  The workarounds help.  Thank you!
