### ISSUE TITLE
How do you set a .NET enum from JavaScript?

### ISSUE THREAD

**Issue by JohnLudlow** [microsoft/ClearScript#156]
How can I set a .NET enum from JavaScript. The common use case is an object with a property of an enum type or method which takes an enum, but here is a simplified (slightly contrived) use case: setting an enum variable.

```csharp
enum Status
{
     Succeeded,
     Failed,
     InProgress,
 }

using (var host = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging, 9002))
{
   host.AddHostType(typeof (Status));
   host.Script.status = Status.Succeeded;
   var a = (host.Evaluate("status"));
   var b = (host.Evaluate("status = Status.Failed"));
}
```
In this case, `b` and `host.Script.status` are undefined. How can we create the correct value from the enum here?

**Comment by ClearScriptLib** [comment]
Hi @JohnLudlow,

The issue here is that `Status` isn't a public type. ClearScript strictly enforces member visibility even for explicitly exposed types.

There are several ways to make the `Status` fields visible to script code. For example, you could make `Status` a public type. Another possibility is to expose it with the private access option:

``` C#
host.AddHostType(HostItemFlags.PrivateAccess, typeof(Status));
```

See [`ScriptEngine.AccessContext`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_AccessContext.htm) for another alternative.

Good luck!

**Comment by JohnLudlow** [comment]
Dang how did I miss that?

Thanks

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or concerns about this topic. Thank you!

**Comment by JohnLudlow** [comment]
Will do, but I think that answers it in terms of enums.

Thanks

**Comment by Brain2000** [comment]
I noticed that I wasn't able to find a function to set an enum from a plain number being passed in, which surprised me. Byte, int32, int64, nullable, string, ScriptObject... so much just works! Since an enum is backed by an int32 by default, I thought it would have been simple to use just a number.

**Comment by ClearScriptLib** [comment]
Hi @Brain2000,

>Since an enum is backed by an int32 by default, I thought it would have been simple to use just a number.

The behavior here is defined by C#, which doesn't implicitly convert integers to enums. Consider this simple example:

``` C#
public enum Kingdom { Plant, Animal };
public class Being { public Kingdom Kingdom; }
```

And then:

``` C#
engine.AddHostType(typeof(Kingdom));
engine.Script.me = new Being();
```

To assign an integer value to `me.Kingdom`, you have to perform an explicit cast, just like in C#. ClearScript provides [`HostFunctions.cast`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_cast__1.htm) for this purpose. To summarize:

``` C#
engine.Script.host = new HostFunctions();
engine.Execute(@"
    me.Kingdom = Kingdom.Animal;         // OK
    me.Kingdom = host.cast(Kingdom, 1);  // OK; explicit conversion
    me.Kingdom = 0;                      // OK; SPECIAL CASE: zero is implicitly convertible to all enums
    me.Kingdom = 1;                      // ERROR
");
```

Good luck!

**Comment by EtienneLaneville** [comment]
I've been getting Type Mismatch errors when trying to use object properties that are enums with VBScript. For example,

`MsgBox object.property`

throws a Type Mismatch exception.

In trying to reproduce this, I wrote the following simple code that uses the Being class and Kingdom enum mentioned in this thread:

```
public enum Kingdom { Plant, Animal };
public class Being { 
    public Kingdom Kingdom = Kingdom.Animal;
}
```
main code:

```
using (var host = new Microsoft.ClearScript.Windows.VBScriptEngine())
{

    Being cat = new Being();
    cat.Kingdom = Kingdom.Animal;

    host.AddHostType(typeof(Kingdom));
    host.AddHostObject("cat", cat);

    host.Execute("MsgBox cat.Kingdom");
    host.Execute("MsgBox cat.Kingdom = Kingdom.Animal");

}
```

The first Execute throws an exception:
_Object doesn't support this property or method: cat.Kingdom_

**Comment by EtienneLaneville** [comment]
Is there a way to get the integer value of an enum on the script side? I can get the name using `.ToString` but I am looking for something like `.ToInt32`. I tried using HostFunctions's `toInt32` method but I get a 'Type mismatch' exception. Since the enum is converted to an object, this makes sense but I am hoping there is a way to somehow get the integer value.

**Comment by ClearScriptLib** [comment]
Hello @EtienneLaneville,

>Is there a way to get the integer value of an enum on the script side?

Sure. You can use `HostFunctions.cast`:

``` C#
engine.AddHostObject("host", new HostFunctions());
engine.AddHostType(typeof(Int32));
engine.Execute("MsgBox host.cast(Int32, Kingdom.Animal)");
```

Another possibility is expose a managed function that performs the conversion:

``` C#
engine.Script.EnumToInt = new Func<Enum, int>(Convert.ToInt32);
engine.Execute("MsgBox EnumToInt(Kingdom.Animal)");
```

>I tried using HostFunctions's toInt32 method but I get a 'Type mismatch' exception.

Right. Those functions are designed for a different purpose – namely, to allow script code to specify the exact numeric type of a host method argument in order to avoid ambiguity in specific scenarios.

>Ideally the `Is` operator would be supported in VBScript `Case` statements

Unfortunately, VBScript's [`Select Case`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/6ef9w614(v=vs.84)) statement only works with numbers and strings. However, it should work in conjunction with one of the suggestions above.

Cheers!
