### ISSUE TITLE
Get access to inner Exception thrown at Host Object

### ISSUE THREAD

**Issue by Nir1812** [microsoft/ClearScript#162]
When using AddHostObject to add CLR object (COM-Visible) with DirectAccess flag set, 
and that host code throws an Exception, this exception is "swallowed" and not passed outside.

The 'try..catch' clause around the call to Execute(...) gets just the outer exception without the InnerException chain.

Is there a way to alter the code and get that exception as the InnerException?

I was looking at this method:  https://github.com/microsoft/ClearScript/blob/d2ff7caa1fe7500c822783feb380f6fd64adde36/ClearScript/Windows/WindowsScriptEngine.cs#L682

and saw that the EXCEPINFO object returned at line 688 and 695 is never used...

Note: I've tried to access ScriptException object (as suggested here: https://github.com/microsoft/ClearScript/issues/39#issuecomment-377545248) but it is 'null' in my case.

**Comment by ClearScriptLib** [comment]
Hi @Nir1812,

>The 'try..catch' clause around the call to Execute(...) gets just the outer exception without the InnerException chain.

If you're talking about an exception thrown by a `DirectAccess` .NET object, then there isn't much that ClearScript can do, since it isn't involved in the script engine's interaction with such an object. Everything is handled by .NET's COM Interop facility, which doesn't preserve the managed exception chain.

COM Interop simply catches any managed exception, converts it into an error code and message, and returns those two items to the unmanaged caller. Eventually the error code and message are returned to the managed host, which synthesizes an exception based on those two items.

We've run a few tests and found that the only difference between ClearScript and the MS Script Control is that the latter preserves the original exception class in some cases, whereas ClearScript always throws [`ScriptEngineException`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptEngineException.htm). Both preserve the original error message but not the managed exception chain.

There are ways to work around this COM limitation. One thing you could do is catch the exception in managed code and store it in a [thread-static](https://docs.microsoft.com/en-us/dotnet/api/system.threadstaticattribute) field, allowing you to access and rethrow it after the script terminates. This is essentially what ClearScript does when you don't use `DirectAccess`.

>the EXCEPINFO object returned at line 688 and 695 is never used...

That object is always empty. The real `EXCEPTINFO` is reported to ClearScript via [`IActiveScriptSite::OnScriptError`](https://docs.microsoft.com/en-us/scripting/winscript/reference/iactivescriptsite-onscripterror). That's how ClearScript obtains the original error message.

Good luck!

**Comment by Nir1812** [comment]
Thanks. I ended up by inheriting my HostObejcts from a base class that implements IReflect interface, and catching the exceptions from within the InvokeMember method into a static Queue...

**Comment by ClearScriptLib** [comment]
Hi @Nir1812,

It's great to hear that you found a solution! We're curious though - does your `IReflect`-based solution reduce any of the `DirectAccess` performance gains?

Thanks!

**Comment by Nir1812** [comment]
I was using the IReflect base class with MSScriptControl, and stopped using it when moved to ClearScript.
But when started using the DirectAccess flag with ComVisible objects, I've decided to put the IReflect implementation back. 
I do not see any performance issues with it, and getting the correct exception trace is a pro.

**Comment by ClearScriptLib** [comment]
Sounds great. Please reopen this issue if you have additional questions about this topic.
