### ISSUE TITLE
Multiple VBScriptEngines sharing documents and debugging code

### ISSUE THREAD

**Issue by Nir1812** [microsoft/ClearScript#163]
I'm using multiple instances of VBScriptEngine in my application, each loads some script code and executes various events. Currently, each engine loads its copy of the code, executes the event, and then disposed.

I'm trying to write a debugger for this, or integrate Visual Studio as a debugger for this app.
When I attach VS to my application, I can see all the engines created, including those engines that ere disposed and supposed to be free... 
Since each event creates a new script engine, loads the code, executes, and being disposed, there is no easy way for me to set a break point and debug the code.

What I'm trying to achieve is to share these script blocks (like code documents) between all the instances, so when I set a break point in one of those documents, it will hit and stop the execution.

Am I on the right track here? Any help or directions for 'first steps' will be very helpful.
Thanks.

**Comment by ClearScriptLib** [comment]
Hi @Nir1812,

>When I attach VS to my application, I can see all the engines created, including those engines that ere disposed and supposed to be free...

Hmm, we don't see disposed engines in the Visual Studio 2019 debugger, at least in the "Script Documents" node in Solution Explorer. Are you using a different version of Visual Studio, or seeing disposed engines elsewhere in the debugger UI?

>What I'm trying to achieve is to share these script blocks (like code documents) between all the instances, so when I set a break point in one of those documents, it will hit and stop the execution.

As far as we know, Windows script engine instances don't share script documents or any other resources, so this may not be possible. One thing you might be able to do is use VBScript's [`stop`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/zw86czy2(v=vs.84)) statement to force a breakpoint from script code.

Good luck!

**Comment by Nir1812** [comment]
I can see the "disposed" engines in the 'Solution Explorer' part in Visual Studio 2019... when running memory profiler, I can see these object has COM references for some reason and that is why they are not disposed.

Can I maybe use [ContinuationCallback](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ContinuationCallback.htm) to stop the script when needed to break?

And one last thing - Is there any way I can start VS are attach it to the script engine automatically?
What will happen if I call the 'Stop' method without any debugger attached?

**Comment by ClearScriptLib** [comment]
>I can see the "disposed" engines in the 'Solution Explorer' part in Visual Studio 2019... when running memory profiler, I can see these object has COM references for some reason and that is why they are not disposed.

Hmm, we can't reproduce that. Are you by any chance creating script engines on one thread and disposing them on another?

Windows script engines have thread affinity, so each must always be invoked on the same thread that created it. ClearScript currently enforces this rule for all methods except `Dispose`, although that just affects the exception that's thrown if the rule is violated.

We're not aware of any other reason why calling `Dispose` wouldn't remove an engine from Visual Studio's list. It doesn't have anything to do with COM references; `Dispose` calls the engine's [`Close`](https://docs.microsoft.com/en-us/scripting/winscript/reference/iactivescript-close) method, which should immediately detach it from the debugger regardless of any outstanding references.

>Can I maybe use `ContinuationCallback` to stop the script when needed to break?

That approach allows you terminate a script rather than pause it, so it's probably not what you want.

>Is there any way I can start VS are attach it to the script engine automatically? What will happen if I call the 'Stop' method without any debugger attached?

When ClearScript was first implemented, if you constructed a VBScript engine with both the `EnableDebugging` and `EnableJITDebugging` flags, `stop` would pop up a dialog that allowed you to launch or attach to a debugger of your choice, stopped at the corresponding line.

Unfortunately this no longer seems to work in newer Visual Studio and Windows versions. You still get the dialog, but it can't launch or attach to a debugger successfully. Your only option is to launch and attach the debugger manually.

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or comments about this topic. Thanks!
