### ISSUE TITLE
Issue with ExpandoObject and ClearScript

### ISSUE THREAD

**Issue by kevinkoenig** [Microsoft/ClearScript#21]
I am having an issue with the ClearScript library.  Here is what I am trying to do:
1.	Create HostObject that has an API
2.	Have the Host API return a dynamic object (ExpandoObject)
3.	Access the dynamic object in JavaScript.
I have written a test program below that demonstrates the approach.  I have made it as simple as possible to demonstrate what I am trying to do.  The code below showcases the JavaScript code that I am executing

![image](https://user-images.githubusercontent.com/4420604/32145021-ebde3de0-bc8f-11e7-9b4b-5e3be76cade4.png)

The object below showcases the TestDynamic object which is very simple

![image](https://user-images.githubusercontent.com/4420604/32145025-f9dffcd0-bc8f-11e7-8c8f-7ec3c8dcc371.png)

When I look at the object created by the host in @Code.  The key here is the extra methods
	Equals(), GetHashCode(), GetType(), and ToString()

![image](https://user-images.githubusercontent.com/4420604/32145026-051da836-bc90-11e7-9cc4-d0eab5bc3b31.png)

In my test program everything works perfectly.
---------------------------------------------------------------------------------
Now in my real solution, I have an asp.net application (Web Forms).  On postback from form (to save) I have a callback mechanism which is invoked in the form lifecycle.  In this instance the callback is the BeforeSave() function below.  I have super simplified the code to eliminate any possible issues.  Right now the code below just calls a corresponding JavaScript method called beforeSave().  I was invoking it dynamically but for now I am directly calling the beforeSave() routine off of the Script object.  As in the test scenario above, the TestDynamic object is exactly the same, so I am not showing the code again.

![image](https://user-images.githubusercontent.com/4420604/32145029-11cfcc30-bc90-11e7-8956-d0e15e72b52c.png)

When I inspect the object from @code, just like in the test project.  I get an exception in the ClearScript below.

![image](https://user-images.githubusercontent.com/4420604/32145033-1cba5a7a-bc90-11e7-8531-e833aa100a85.png)

The exception below is what is being thrown

![image](https://user-images.githubusercontent.com/4420604/32145038-2b179eca-bc90-11e7-89e7-2f17b014201b.png)

Three exceptions are thrown.  If you inspect the args parameter of the Invoke method, you see the following methods that are excepting.
args[0] = “ToString”
args[0] = “Equals”
args[0] = “GetHashCode”

Here is the call stack when the exception is thrown.
![image](https://user-images.githubusercontent.com/4420604/32145045-39a0f5a4-bc90-11e7-910e-ea37be286a56.png)

I have tried to trace through the code to see how these methods are added to the ExpandoObject that I am creating.  I cant figure it out.  Any help would be great.  Thanks in advance.

**Comment by ClearScriptLib** [comment]
Hi @kevinkoenig,

Thanks for providing all that information. We believe that the behavior you're seeing is by design.

1. The "extra" methods are inherited from the ultimate base class [`System.Object`](https://docs.microsoft.com/en-us/dotnet/api/system.object). In the managed domain these methods are unusual in that they're _always_ accessible, even when the static type is anonymous, external, [`dynamic`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic), an interface, etc.

1. The exceptions are due to the way dynamic objects work in ClearScript. When the script engine requests member evaluation for a dynamic object, ClearScript first attempts to fulfill the request via the object's [`IDynamicMetaObjectProvider`](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.idynamicmetaobjectprovider) implementation. For members defined statically, such as normal compiled methods, this attempt fails and an exception is thrown. ClearScript catches the exception and falls back to normal member binding. In other words, the exception should be handled internally without affecting your application, and in the debugger it should be safe to disable first-chance handling ("Break when this exception type is thrown").

**Comment by kevinkoenig** [comment]
First let me just thank you all for the quick responses.  The support on this library is really great.  

I normally run with all exceptions on in our core product as I find that many people ignore real issues that are swallowed using exceptions.  Then I turn them off as I understand them.

I probably spent 3 days trying to debug the issue assuming there was something wrong with my application.  I can say I learned a lot about dynamics and how ClearScript supports them, so the time wasn't entirely wasted 👍. 

I guess the issue is that while I was debugging inside ClearScript a request timed out which caused @Code to display 'unknown' for every member of the object I as returning.

I have it all back together now and it is working perfectly (now that I disabled those exceptions)

Kevin
