### ISSUE TITLE
How to run a VBScript from C# using ClearScript

### ISSUE THREAD

**Issue by egkareem** [microsoft/ClearScript#216]
Hello
In trying to understand how things work in ClearScript I searched and studied some of the test cases and other documents in the web, I was not very successful in understanding how I could do this:

How to run a VBScript from C# using ClearScript

I came up with the following code, it contains a code with different variables in the VBScript. I want to:
1. Execute the code in stirng parmCode
2. Be able to access all variables inside the script after it has finished execution.

I also tried Execute method, but got syntax error when using TryGetValue

Please help, if possible direct me to an 101 guide, as the current info is scarce and complex.

```
try
            {
                parmCode = "DIM pi  : pi=4*ATN(1)"; //used : to separate statements
                using (var vbEngine = new VBScriptEngine()) //<-- causes syntax error
                {

                    var result=vbEngine.Evaluate(parmCode);
                    dynamic dynamicResult = result;

                    Console.WriteLine(dynamicResult.pi);

                    foreach (var name in dynamicResult.GetDynamicMemberNames())
                        Console.WriteLine("{0}: {1}", name, dynamicResult[name]);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return null;
            }
```

**Comment by ClearScriptLib** [comment]
Hi @egkareem,

The [`Evaluate`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_ScriptEngine_Evaluate.htm) method directs VBScript to process script code as an _expression_ rather than a sequence of _statements_. In this context, `DIM` is illegal, and `=` performs an equality test rather than variable assignment.

To execute code as a sequence of statements, use [`Execute`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_ScriptEngine_Execute.htm) instead:

``` C#
using (var vbEngine = new VBScriptEngine()) {
    vbEngine.Execute("DIM pi : pi=4*ATN(1)");
    Console.WriteLine(vbEngine.Script.pi);
}
```

>Please help, if possible direct me to an 101 guide, as the current info is scarce and complex.

Take a look at the [ClearScript FAQtorial](https://microsoft.github.io/ClearScript/Tutorial/FAQtorial.html).

Good luck!

**Comment by egkareem** [comment]
Thank you for your answer. I will read the FAQtorial again, although it is a advanced for me. I wish someone writes more elementary material on this powerful tool.
Sure you can close this question now. 
Thanks again.
