### ISSUE TITLE
Need an option to wait for a debugger connection

### ISSUE THREAD

**Issue by Muchaszewski** [Microsoft/ClearScript#22]
V8ScriptEngine with flags EnableDebugging or/and EnableRemoteDebugging do not wait for debugging engine to connect when `debugger` method is provided in javascript
```csharp
Engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging | V8ScriptEngineFlags.EnableRemoteDebugging);
Engine.Execute("debugger;");
```
EDIT
I will double chcek which version V8 I'm currently using
EDIT
Happens on version 6.2.414.40

**Comment by ClearScriptLib** [comment]
Hi @Muchaszewski,

The [`debugger`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger) statement doesn't wait for a debugger connection. It pauses execution if a debugger is attached; otherwise it does nothing. There's no way for ClearScript to change its behavior.

We've confirmed that Node.js behaves the same way; that is, `debugger` does nothing unless a debugger is attached.

On the other hand, Node.js has an option to wait for a debugger connection (and set up a break) before executing the first line of JavaScript code. ClearScript would definitely benefit from a similar option.

**Comment by Muchaszewski** [comment]
This was the case in version 5.4 where not having debugger connected would wait for it connect even if no debugger was connected at the time when `debugger` instruction in code execution was reached.

What is the current recommended way to break execution of javascript code for debugging process?

**Comment by ClearScriptLib** [comment]
@Muchaszewski Once you've instantiated `V8ScriptEngine` or `V8Runtime` with debugging enabled, you can attach a debugger at any time, even when the engine is not running script code.

**Comment by Muchaszewski** [comment]
@ClearScriptLib Thanks for fast and reliable responses.
Unfortunately, I'm unable to debug using VSCode anymore.

As you have mentioned I have set a breakpoint after ScriptEngine initialization and then I'm connecting using VSCode with "inspector" mode. 
Then I have resumed C# code to hit `Compile` and `Execute` where the script has `debugger` instruction. This "pauses" C# code because as you have mentioned it waits for debugger input, but VSCode does not show any script to debug. 
Expected behavior was the one I have seen in 5.4 where VSCode has opened "Script Document" with currently executed code. I will also mention that I'm unable to open any documents from "Loaded Scripts" section of VS Code.
Do you think that this is ClearScript error or VSCode debugger itself? I can open a new ticket with more information provided if you think this is the ClearScript bug.

**Comment by ClearScriptLib** [comment]
Hi @Muchaszewski,

Hmm, you've described a number of things that we can't reproduce.

First, when your application is stopped in a .NET or native debugger, it can't establish a connection to a script debugger, because doing so involves running .NET and native code. If you try to attach VSCode at that point, it'll just sit there waiting for your application to respond. Is that not what you're seeing?

Second, if you've stopped your application just before it executes a `debugger` statement, then resuming it isn't likely to establish a debugger connection quickly enough for the statement to have any effect. That's just theory of course, but it's exactly what we observed every time.

Third, we can't reproduce the state in which VSCode has successfully paused script execution but cannot display the script code.

As we're now using this issue to track the "attach and break on first line" feature, please create a separate issue if you can't resolve the problem. Please include as much information as possible, including your OS version(s), VSCode debugging configuration, and the exact steps for reproducing the problem.

Thank you!

**Comment by ClearScriptLib** [comment]
Added [`V8ScriptEngineFlags.AwaitDebuggerAndPauseOnStart`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8ScriptEngineFlags.htm) in [Version 5.5.1](https://github.com/Microsoft/ClearScript/releases/tag/5.5.1).
