### ISSUE TITLE
Passing host arrays as JS arrays

### ISSUE THREAD

**Issue by Alainx277** [microsoft/ClearScript#228]
When invoking a JS function and passing a C# array, it is not an actual JS array (Array.isArray returns false).

In my concrete case it prevents me from using array methods like map or filter.
Is there anyway I can pass the host array as a plain JS array or at least get the native array methods to work?

**Comment by ClearScriptLib** [comment]
Hi @Alainx277,

ClearScript's longstanding policy is to never perform implicit conversion if it's lossy, at least by default, unless the lack of such conversion makes using ClearScript exceptionally painful.

That's why it implicitly converts only fundamental data types – numbers, strings, etc. Recent releases have added optional implicit date-time and task-promise conversion by request; perhaps arrays should be next.

In the meantime, you can easily add a .NET method for this purpose. Here's an example:

``` C#
public static class ArrayExtensions {
    public static object ToScriptArray(this Array array, ScriptEngine engine) {
        return engine.Script.Array.from(array);
    }
}
```

And here's how you might use it:

``` C#
var array = new[] { 1, 2, 3, 4, 5 };
Console.WriteLine(engine.Script.Array.isArray(array.ToScriptArray(engine)));
// writes "True"
```

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or concerns. Thanks!

**Comment by gjvdkamp** [comment]
I'm returning an array from a static class that doesn't have a handle to the engine, the engine only gets it a a static type. 

engine.AddHostType("xlc", typeof(JsXlcProxy));

Is there any other way to do this conversion or should I set a static handle to the engine on that host type too?

**Comment by CrosRoad95** [comment]
having issue with Script.Array.from:
![image](https://user-images.githubusercontent.com/22455534/194764499-df0c2f78-afef-416b-9b34-bd68667dc043.png)
code:
![image](https://user-images.githubusercontent.com/22455534/194764519-f44bdecc-6159-4098-8f98-abe59a994e7a.png)
what am i doing wrong? i just streight copied your example, "ScriptEngine.Current.Script.Array.from" - there's no null reference problem

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

Are you by any chance using .NET 7 Preview? Some versions have [bugs](https://github.com/microsoft/ClearScript/issues/406) that cause this issue.

Thanks!

**Comment by CrosRoad95** [comment]
no, this project setting is following: `<TargetFramework>net6.0</TargetFramework>`

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

>i noticed that CustomAttributeLoader cause this issue

Attributes, when applied broadly via a custom loader, can indeed interfere with some ClearScript features. Can you describe what your custom loader does?

Cheers!

**Comment by CrosRoad95** [comment]
```csharp
class LowercaseSymbolsLoader : CustomAttributeLoader
{
    public override T[]? LoadCustomAttributes<T>(ICustomAttributeProvider resource, bool inherit)
    {
        var declaredAttributes = base.LoadCustomAttributes<T>(resource, inherit);
        if (!declaredAttributes.Any() && typeof(T) == typeof(ScriptMemberAttribute) && resource is MemberInfo member)
        {
            return new[] { new ScriptMemberAttribute(member.Name.ToTypescriptName()) } as T[];
        }
        return declaredAttributes;
    }
}
```
thats the loader, extension method "ToTypescriptName" is:
```csharp
    public static string ToTypescriptName(this string str)
    {
        return char.ToLowerInvariant(str[0]) + str[1..];
    }
```

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

Thanks for posting your sample code. What you're seeing is a bug. We're tracking it as Issue #423, and the next ClearScript release will include a fix.

In the meantime, the only way to work around this issue is to exclude several resources from your custom attribute loader. You can do that as follows:

``` C#
public class LowercaseSymbolsLoader : CustomAttributeLoader {
    public override T[] LoadCustomAttributes<T>(ICustomAttributeProvider resource, bool inherit) {
        var declaredAttributes = base.LoadCustomAttributes<T>(resource, inherit);
        if (IsProtectedResource(resource)) {
            return declaredAttributes;
        }
        if (!declaredAttributes.Any() && typeof(T) == typeof(ScriptMemberAttribute) && resource is MemberInfo member) {
            return new[] { new ScriptMemberAttribute(member.Name.ToTypescriptName()) } as T[];
        }
        return declaredAttributes;
    }
    private static bool IsProtectedResource(ICustomAttributeProvider resource) {
        if (resource is MemberInfo member && member.DeclaringType != null) {
            if (member.DeclaringType.Assembly.GetName().Name == "ClearScript.Core") {
                return true;
            }
            var typeName = member.DeclaringType.FullName;
            return
                typeName.StartsWith("System.Collections.Generic.IAsyncEnumerator") ||
                typeName.StartsWith("System.Collections.Generic.IEnumerator") ||
                typeName == "System.Collections.IEnumerator" ||
                typeName == "System.IDisposable";
        }
        return false;
    }
}
```

Unfortunately, this workaround prevents custom attributes from being applied to several public .NET resources, such as `IDisposable.Dispose`. Our official fix should be fully transparent.

Thanks again for reporting this issue!
