### ISSUE TITLE
Array operator overloading with enums

### ISSUE THREAD

**Issue by Alainx277** [microsoft/ClearScript#229]
When overloading the [] operator in a class, and having it indexed by an enum, accessing it from JS results in an exception: 
`Microsoft.ClearScript.ScriptEngineException: Error: The object has no suitable property or field named '[object Object]'`

Simple example:
```csharp
[Flags]
public enum SampleEnum
{
	None = 0,
	Something
}

public class SampleClass
{
    public float this[SampleEnum sample]
    {
      get
      {
        return 0f;
      }
      set
      {
        // do nothing
      }
    }
}
```
```javascript
var sample = new SampleClass();
sample[SampleEnum.Something] = 1f; // crashes
```

I would expect that the enum would be recognized as a host type and then used to access the overload.

**Comment by ClearScriptLib** [comment]
Hi @Alainx277,

C# and JavaScript assign entirely different semantics to bracket syntax. In C#, brackets are used to invoke indexers, whereas in JavaScript they're simply an alias for property access.

The JavaScript syntax `foo['bar']` is 100% equivalent to `foo.bar`. In your case, since `SampleEnum.Something` isn't a string, V8 first calls `toString`, yielding "[object Object]", and then directs ClearScript to retrieve a property with that as its name. The operation fails because no such property exists. Unfortunately there's no way to override V8's behavior in this scenario.

On the C# side, your custom indexer actually creates an _indexed property_ named "Item". Such properties are strongly typed, overloadable, and can have multiple parameters, so even if we could override V8's handling of JavaScript's bracket syntax, it would still be fundamentally inadequate for the task.

Instead, ClearScript supports the following JavaScript pattern for accessing C# indexers. It's clunky, but it supports all the capabilities of .NET indexed properties.

``` JavaScript
value = object.Item.get(arg0, arg1, ...); // OR object.Item(arg0, arg1, ...)
object.Item.set(arg0, arg1, ..., value);
```

In your case, that would be: 

``` JavaScript
sample.Item.set(SampleEnum.Something, 1); // works
```

Notes:
- Some .NET languages can create indexed properties with names other than "Item". The syntax above should support them.
- ClearScript does support C#-style numeric indexing for objects that implement [`IList`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist) or [`IList<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ilist-1), including C# arrays. It does that by projecting artificial properties with numeric names.

Cheers!

**Comment by Alainx277** [comment]
That makes sense, thanks!
