### ISSUE TITLE
VBScript code cannot access nested types

### ISSUE THREAD

**Issue by NickJWilliams** [Microsoft/ClearScript#23]
Hello,

I have just discovered ClearScript, and think it's great. But I am having trouble exposing _enums_ and _consts_ to my scripts. 

**for example:** I created a basic class with an enum defined.
```
Public Class test
    Public Enum Numbers
        one
        two
        three
    End Enum
End Class
```

I then add this to my engine

`scriptEngine.AddHostType("test", GetType(test))`

but I am unable to reference numbers in my scripts e.g.

`test.Numbers.one`

I would expect this to be an integer with a value of one? But instead get an error 

> Public member 'Numbers' on type 'HostType' not found.

Does ClearScript support enums? Any help appreciated.

Thanks

**Comment by ClearScriptLib** [comment]
Hi @NickJWilliams,

ClearScript does support enums, but you found a bug. This bug affects only nested types, and only when accessed from VBScript. You can work around it by exposing your nested type directly:

``` VB
scriptEngine.AddHostType("test", GetType(test))
scriptEngine.AddHostType("Numbers", GetType(test.Numbers))
```

Unfortunately this means that your script code will have to use `Numbers.one` instead of `test.Numbers.one` for now. We'll post a fix shortly. Thanks for reporting this bug!

One more thing. ClearScript does **not** expose enums as integers. Its aim has always been to give script code full access to all the capabilities of exposed .NET objects, and since .NET enums are **not** integers, it wouldn't be correct to expose them as such. One consequence of this is that you must use [`is`](https://msdn.microsoft.com/en-us/library/ake1y5wx(v=vs.84).aspx) to compare them instead of the equality operator.

Good luck!

**Comment by NickJWilliams** [comment]
Glad I could help :-)

Just wondering how I can use the enum values in a bit wise scenario? e.g. 

`somefunc.test = Numbers.one + Numbers.two`

Thanks
Nick

**Comment by ClearScriptLib** [comment]
@NickJWilliams Unfortunately ClearScript can neither override VBScript's operators nor expose .NET's. It provides the generic [`HostFunctions.flags`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_flags__1.htm) for combining bitwise enum members, but if that's not sufficient, you'll have to expose a helper class or some functions that perform these operations in managed code.

**Comment by NickJWilliams** [comment]
Thanks, lastly should I be able to access Const's in my host objects/types?

**Comment by ClearScriptLib** [comment]
@NickJWilliams If the constant is a public member of an exposed class, structure, or module, it should be accessible from script code.

**Comment by NickJWilliams** [comment]
Hi thanks for fixing my issue, how do I go about updating my project. I am currently referencing ClearScript via NuGet. 

I am also having trouble creating new instances of objects from defined types. 

e.g.

```
Dim obj
set obj = new test
```
I am getting 

> Class not defined: 'test'

Thanks 
Nick

**Comment by NickJWilliams** [comment]
Just to add to the above, I thought I would try using `Microsoft.ClearScript.Windows.JScriptEngine`.

This appears to work as expected. But we need to use VBScript as other applications we are working with use VBScript and ideally we want to keep everything consistent.

Thanks
Nick

**Comment by ClearScriptLib** [comment]
Hi Nick,

We don't provide ClearScript binaries. You can try contacting the NuGet project owners or building ClearScript yourself (instructions [here](https://microsoft.github.io/ClearScript/Details/Build.html)).

Unfortunately, unlike JScript, VBScript doesn't allow the host to override the `new` keyword, but ClearScript provides a function for instantiating host types:

``` C#
engine.Script.host = new HostFunctions();
engine.AddHostType(typeof(test));
engine.Execute(@"
    set obj = host.newObj(test)
");
```

If you need to interface with legacy code that uses `new`, you can create a VBScript wrapper class for your host class.

Good luck!
