### ISSUE TITLE
example  can not work

### ISSUE THREAD

**Issue by gitlsl** [microsoft/ClearScript#237]
I am new user with ClearScript and get error with example  from `https://microsoft.github.io/ClearScript/Examples/Examples.html`

get error at `engine.AddHostObject("lib", new HostTypeCollection("mscorlib", "System.Core"));`
`System.IO.FileNotFoundException:“ with System.Core`

if remove "System.Core"  , this line OK , but `use LINQ from script`   will get error 
`Microsoft.ClearScript.ScriptEngineException:“TypeError: numbers.Where is not a function”`

my env: .net 4.8   ClearScript:7.1.1

**Comment by ClearScriptLib** [comment]
Hi @gitlsl,

We just tested the example code on several machines and did not encounter any issues. We used ClearScript 7.1.1 on .NET Framework 4.8, .NET Core 3.1, and .NET 5.0. Could there be a problem with your .NET installation?

One thing you could try – and this is actually the recommended approach – is to initialize `HostTypeCollection` with assemblies instead of names:

``` C#
engine.AddHostObject("lib", new HostTypeCollection(
    typeof(string).Assembly,
    typeof(Enumerable).Assembly,
    typeof(ExpandoObject).Assembly
));
```

Please let us know if this still doesn't work for you, or if you have additional thoughts or findings.

Thanks!

**Comment by gitlsl** [comment]
The. Net installation environment should be OK. Is it a problem of different system languages（I 
 am  chinese）? I use core5.0 still display error and recorded a video for you
[test.zip](https://github.com/microsoft/ClearScript/files/6088387/test.zip)

**Comment by gitlsl** [comment]
Maybe my debug plug-in caught it the internal exception in `engine.Execute` ,so break offten,  
after disable it, the demo work fine, but there many warnings  in output window:` ' Microsoft.CSharp.RuntimeBinder .RuntimeBinderException' inMicrosoft.CSharp.dll`

**Comment by ClearScriptLib** [comment]
Hi @gitlsl,

Thanks for sharing the video! We've reproduced the behavior in the debugger.

As far as we can tell, there's nothing wrong here. ClearScript and other components throw and handle exceptions internally as a matter of course. If you configure your debugger to stop whenever any exception is thrown, it'll stop quite often. As long as no unexpected exceptions are reaching your application code, that's normal behavior.

Note also that the example code exposes a very large set of .NET resources for scripting, including a large number of extension methods. That greatly increases the number of exceptions thrown during the method binding process, in which ClearScript invokes components of the C# compiler to associate managed methods with the names requested by script code.

Cheers!

**Comment by gitlsl** [comment]
thanks for your explain, I understand the reason for the Exception, but how about `can not see any  local variables in Locals or Watch window` , only show `Internal error in the c# compiler`
I test some jsengine like `jint`, it can see variables  when hit breakpoint;

**Comment by ClearScriptLib** [comment]
@gitlsl You're welcome!

If you're still having issues with local variables in the debugger, please understand that ClearScript is not involved with the implementation of any C# debugging features, so the problem is likely elsewhere.

If you're talking about viewing JavaScript variables, see [here](https://microsoft.github.io/ClearScript/Details/Build.html#_Debugging_with_ClearScript_2) for an overview of debugging JavaScript with V8.

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or issues related to this topic. Thank you!
