### ISSUE TITLE
Automatically marshal JS functions to Actions and Functions in c#

### ISSUE THREAD

**Issue by dpeter99** [microsoft/ClearScript#240]
I'm trying to switch my JS engine to V8 from Jint, as Jint doesn't seam to provide debugging options for VSCode. In Jint if I call a c# functiont that takes in an ``Action<int>`` with a function as the parameter, it is automatically converted. I know ``host.proc`` exists but i would like to make the transfer as seamless to my users as possible, and the use of an extra function call for this is quite un natural for JS users.

**Comment by ClearScriptLib** [comment]
Hello @dpeter99,

Jint appears to use Reflection-based method binding, whereas ClearScript uses the C# Runtime Binder. The latter provides correct overload selection and supports generic methods, but it requires a more exact signature match for binding to succeed. Because JavaScript functions can't be mapped to specific delegate types, they don't work as arguments for delegate-typed parameters.

However, there's no need for your users to call `host.proc` or a similar method. You can easily provide an overload or extension method that works directly with JavaScript functions. Suppose your class looks like this:

``` C#
public class Foo {
    public void DoSomething(Action<int> action) {
        ...   
    }
}
```

Script code can't invoke `DoSomething` and pass in a script function. However, you can easily add an overload for that purpose:

``` C#
public class Foo {
    public void DoSomething(Action<int> action) {
        ...
    }
    public void DoSomething(dynamic func) {
        DoSomething(arg => func(arg));
    }
}
```

And now script code can call `DoSomething` as intended:

``` C#
engine.AddHostObject("foo", new Foo());
engine.Execute(@"
    foo.DoSomething(function (arg) {
        ...
    })
");
```

Good luck!

**Comment by dpeter99** [comment]
Hi!
Thanks that did work!

I do have some quetions regarding similar problems. I posted about them in #243
