### ISSUE TITLE
Allow automatically converting between numerical types when calling a host method

### ISSUE THREAD

**Issue by KurtGokhan** [microsoft/ClearScript#266]
This works:

```csharp
        public void Test_AutoFloatToDouble()
        {
            engine.AddHostType("Convert", typeof(Convert));
            engine.Script.list = new List<double>();
            const float floatPi = (float) Math.PI;
            engine.Execute("list.Add(Convert.ToSingle(Math.PI))");
            Assert.AreEqual(floatPi, engine.Script.list[0]);
        }
```

While this does not:

```csharp
        public void Test_AutoDoubleToFloat()
        {
            engine.Script.list = new List<float>();
            engine.Execute("list.Add(Math.PI)");
            Assert.AreEqual(Math.PI, engine.Script.list[0]);
        }
```

This is as expected, because `double -> float` is a lossy conversion. However, it can be troubling to write `Convert.ToSingle` everytime when calling a host method if the host method expects float. Also because JS only has 1 number type and it is not as convenient as C# where you can write `1.25f` to create a float. I think ClearScript should add an option to allow automatically converting between numerical types, even if it's a lossy conversion.

**Comment by ClearScriptLib** [comment]
Hi @KurtGokhan,

To correctly support overloaded methods, generic methods, output parameters, implicit conversions, and other features, ClearScript relies on the [C# Runtime Binder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.csharp.runtimebinder) – a partial implementation of the C# compiler available at runtime. The C# method binding algorithm is particularly complicated, so ClearScript doesn't attempt to duplicate it.

That means, unfortunately, that ClearScript can't easily change the rules of method binding, which are very strict when it comes to numeric data loss. It might be possible to attempt binding once for each combination of original and narrowed arguments, but that would add significant cost to an already expensive operation.

We can offer a couple of suggestions. First, you could add a script-friendly overload or extension method:

``` C#
public static class Extensions {
    public static void Add(this List<float> list, double item) => list.Add((float)item);
}
```

And then:

``` C#
engine.AddHostType(typeof(Extensions));
engine.Script.list = new List<float>();
engine.Execute("list.Add(Math.PI)");
```

Second, although JavaScript doesn't support `123.456789f`, you can get pretty close:

``` C#
engine.Script.list = new List<float>();
engine.Execute(@"
    const f = Math.fround;
    list.Add(f(123.456789));
");
```

By the way, we recommend [`Math.fround`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/fround) over [`Convert.ToSingle`](https://docs.microsoft.com/en-us/dotnet/api/system.convert.tosingle) or [`HostFunctions.toSingle`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_toSingle.htm) because it avoids a round trip across the expensive host-script boundary.

Good luck!

**Comment by KurtGokhan** [comment]
i figured it was something along those lines. Thank you for confirming. The workarounds you proposed seem helpful. I will try.
