### ISSUE TITLE
how to impove performance of host object call

### ISSUE THREAD

**Issue by coader** [microsoft/ClearScript#267]
if call host object's mehtod or property in script, it will much slow than call javascript object, maybe diff with 100X times
how to improve it? is it use reflection to call host object now?

**Comment by ClearScriptLib** [comment]
Hi @coader,

Yes, calling a host object is very expensive, especially if you're using V8, where the difference is comparatively huge due to V8's hyper-optimized native JavaScript property access.

The first call to a given host method is particularly expensive, as that's when the _method binding_ process takes place, which uses reflection, compilation, and other techniques to identify the most suitable target method.

ClearScript does a lot of caching to reduce the average overhead – constant-valued fields, enum tokens, method binding results, etc. – but there's only so much it can do without knowing the details of your application.

As an application developer, there isn't much you can do to accelerate calls across the host-script boundary. Instead, think about ways to reduce the frequency of such calls. In other words, consider implementing part of your host API in JavaScript.

Here's a simple example. Suppose you'd like to enable the following JavaScript code:

``` JavaScript
var request = new Request();
request.Uri = 'http://www.example.com';
request.Body = 'Hello, world!'
request.Send();
```

One way to do that is to expose a managed `Request` class:

``` C#
public class Request {
    public string Uri { get; set; }
    public string Body { get; set; }
    public void Send() {
        // send request using Uri and Body
    }
}
[...]
engine.AddHostType(typeof(Request));
```

Note that your JavaScript code requires three host object calls in order to do its job. Here's a better way to go:

``` C#
public class RequestHelper {
    public void Send(string uri, string body) {
        // send request using uri and body
    }
}
[...]
dynamic setup = engine.Evaluate(@"(
    function (helper) {
        Request = class {
            Send = () => helper.Send(this.Uri, this.Body);
        };
    }
)");
setup(new RequestHelper());
```

Now the same JavaScript code does the same job with only one host object call.

That's just a simple example, but hopefully you can see how the host and script engine can work together to provide an optimized API for script code.

Good luck!

**Comment by coader** [comment]
thanks, yes, i have a  host type like ado dataset, it will be visited many times in js
so I plan to transfer it's data as json and parse it in js, but thus will bring a lot works.

and about reflection, I use Expression.Lambda in my own project, it will be faster, not sure if clearscript alos use solution like this.

at last, if script engine has a Func<...> property, let us to decide how to access method or property, like this:

`engine.VisitHostObject=Func<object, methodname,parameters>
{
if (methodname=="Send"){
  return .....
}
}`

we only process those method effect key performance

**Comment by ClearScriptLib** [comment]
Hi @coader,

>I use Expression.Lambda in my own project, it will be faster, not sure if clearscript alos use solution like this.

ClearScript doesn't compile lambda expressions to accelerate invocation. We don't know whether that approach would work for all supported scenarios (`out`/`ref` parameters, `params` arrays, generic methods, etc.), nor is it clear how any improvement would compare to the cost of jumping from native to managed code.

>if script engine has a Func<...> property, let us to decide how to access method or property

That's an interesting idea, but again, that's a managed-only mechanism, whereas we believe that most of the cost is due to hopping across the native-managed boundary.

Thanks!

**Comment by coader** [comment]
if any method to load compiled js function or module? 
so I  can parse and compiled this function once, and load it for diff script, 
thus will let us create functions and use it as same as built-in, 
before: 
c#
public DataContainer{
  public DataContainer(DataTable table){
 }
public object GetData(string field){
return ...
 }
}

after:
js:
function dataContainer(json){
   const data=JSON.parse(json)
  function getData(field){
    .....
  }
}

compiled this function and use it for all scripts.

**Comment by ClearScriptLib** [comment]
Hi @coader,

V8 doesn't support compiling scripts to a form suitable for offline storage. However:

1. In a given engine instance, different scripts can reuse the same functions and objects as long as those resources remain reachable from the global object. That is, if you're running all your scripts in the same engine instance, you shouldn't need to set up your script API more than once.

2. You can use [`Compile`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_Compile_3.htm) et al to create script artifacts that can be re-executed without recompilation. Compiled scripts are valid for all `V8ScriptEngine` instances that share a [runtime](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8Runtime.htm), but they can't be stored offline and aren't valid across process boundaries.

3. You can use a [cache data](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8Runtime_Compile_2.htm) to accelerate script [recompilation](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8Runtime_Compile_7.htm). Cache data _can_ be stored offline and is valid for reuse in subsequent sessions, but it's limited to the V8 version that created it.

Good luck!
