### ISSUE TITLE
Random crashes on creating new instance of  'V8ScriptEngine' - WPF

### ISSUE THREAD

**Issue by GameHackerPM** [microsoft/ClearScript#268]
Currently my situation is different, I use it on a web scrapper which is doing multi-threading process and on more than 1 process of the same program (I open 3-4 processes of the program at the same time), It works fine and everything is totally fine, but after some time I see the program crashes without any details or catching any exceptions with "UnhandedException Event" for the application, when I tried on debug mode for the program (one of the processes) I got this exception: 

![Image](https://i.ibb.co/5G9LBST/image.png)

As you can see, I tried using "Lock" for it but seems the same issue, also noticed that when I open 3 processes of the program, the first one is always getting high CPU usage than others and also getting memory leak, but other processes don't do that at all, they work fine without any high CPU usage or memory leak stable and fine..!

Any advice in that.. P.S: Using version 7.1.3.

Thanks for the nice tool! ^^

**Comment by ClearScriptLib** [comment]
Hi @GameHackerPM,

Unfortunately we can't diagnose your issue without more information.

Can you provide a complete minimal code sample that reproduces the problem? If not, consider [enabling crash dumps](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) for your application. Use the Full dump type. If you're comfortable sharing a crash dump, we'll be happy to take a look.

Some general comments:

1. Script engines are thread-safe, so you shouldn't need a lock unless you're using it to protect your own (rather than ClearScript's) resources.

2. Script engines in different processes are isolated from each other, so multiple instances of your applications shouldn't be able to affect each other unless they somehow communicate across process boundaries.

3. In the code above, the `using` statement makes the `Dispose` call unnecessary.

Thanks!

**Comment by GameHackerPM** [comment]
Hi @ClearScriptLib,

Thanks for the fast reply.

I have tried to enable crash dumps from regedit as explained in the link, but didn't generate anything, do I need to restart the system after that?
But I created a dump file through Task Manager as well when it crashed, Here is the dump you requested: https://www.filemail.com/d/vyvrwbwdiygycuy

Thanks for the general comments/tips.

**Comment by ClearScriptLib** [comment]
Hi @GameHackerPM,

Thanks for sharing the crash dump! We've managed to reconstruct the crash stack, but it's a real head scratcher.

We have a theory about the cause, but since we can't reproduce the crash, we can't test it. Would you be willing to test one or more patched assemblies? If so, what runtime are you using (.NET Framework, .NET Core, .NET 5, etc.)?

Cheers!

**Comment by GameHackerPM** [comment]
Hi @ClearScriptLib,

Thanks for the reply.

Currently, I'm using .NET Framework 4.8, also tried with .NET Framework 4.6.2 was the same thing. Ya I think I can test whatever you like to find what's wrong with it and fix that issue if it's from my side or something wrong with ClearScript. Will be glad to help you out for finding this.

Best Regards..

**Comment by ClearScriptLib** [comment]
Hi @GameHackerPM,

Please try the following patched assembly on .NET Framework 4.8: [ClearScript.V8.dll.zip](https://github.com/microsoft/ClearScript/files/6701741/ClearScript.V8.dll.zip). Make sure to replace your deployed version of ClearScript.V8.dll with this one. In the Details tab of the Properties dialog, "Product version" should be "7.1.3-patch1".

Thanks for your help!

**Comment by GameHackerPM** [comment]
Hi @ClearScriptLib,

Just to let you know, I'm testing that patch will leave it for another day just to make sure it fixed the issue before I confirm with you, but thanks for the follow and fast reply..
Will let you know the final reply if it crashed again. 

Best regards.

**Comment by GameHackerPM** [comment]
Hi @ClearScriptLib,

I can confirm that this patch fixed the issue which was randomly crashing, I tested it for 6 hours straight no crashes at all. Before that test there is another test for 3 hours got crashed, but sadly can't confirm it's from ClearScript or something else specially that 20 instances of the program on 10 different devices got closed at the exact same time without even giving any crash message or anything. 

So I would suggest this patch fixed the issue fine. I hope you can push that to public version so I can update it directly. 

Thanks a lot for your help and fast patching. [I have left the issue open until you confirm and close it yourself!]

Best Regards.

**Comment by ClearScriptLib** [comment]
Hi @GameHackerPM,

Thank you very much for testing the fix! The other issue doesn't _sound_ like it's related to ClearScript, but if you think it could be, don't hesitate to send us another crash dump.

We'll post a new release ASAP.

Thanks again!

**Comment by ClearScriptLib** [comment]
[Version 7.1.4](https://github.com/microsoft/ClearScript/releases/tag/7.1.4) includes the fix. Thanks again!
