### ISSUE TITLE
Odd behavior with numbers - Lossy conversion. Any way to bypass ClearScript's type conversion?

### ISSUE THREAD

**Issue by mattezell** [microsoft/ClearScript#270]
Hello again, ClearScript.

I've been banging my head against an issue that seems as if it should be relatively trivial, yet...

I'm hoping someone can shed some light on what I'm seeing...

Consider the following (sorry if there are errors - I'm working in a proprietary codebase and so can't copy/paste to share):

```
var engine = runtime.CreateScriptEngine();

engine.AddHostObject("clr", new HostTypeCollection("System"));

var res = engine.Evaluate("(function(){ return clr.System.String.Format(\"{0:###,###,###.00}\", 123123.75); })()");

Console.WriteLine(res);
```

The above will result in "123,123.80" rather than the desired "123,123.75".

Similarly, the following will result in 123,123.80:
```
engine.Evaluate("(function(){ return clr.System.Convert.ToDecimal(123123.75); })()");
```

While the following will result in the desired correct value of 123123.75:
```
engine.Evaluate("(function(){ return clr.System.Convert.ToDouble(123123.75); })()");
```

After wading through ClearScript source, I'm thinking this likely has to do with some conversion to a Single... Is this correct? If so, is there a way to bypass this conversion for marshaling?

No matter what I try, I can find no magical combination of JSON.stringify or System.Covert.* that will prevent this mangling/rounding from within the JavaScript execution context (I wish I could just handle it in the C# codebase, but that's not an option for this product)...

Any assistance is greatly appreciated!
-Matt

**Comment by ClearScriptLib** [comment]
Hi @mattezell,

Hmm. The `double` value 123123.75 appears to be convertible to `float` without data loss, but .NET can't format the resulting value to a string correctly. We're stumped.

In any case, you can use [`HostFunctions.toDouble`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_toDouble.htm) to work around this issue:

``` C#
engine.AddHostType(typeof(Console));
engine.AddHostObject("host", new HostFunctions());
engine.Execute("Console.WriteLine('{0:###,###,###.00}', host.toDouble(123123.75))");
```

Good luck!

**Comment by mattezell** [comment]
As always, y'all are awesome as is the project!  Thank you for helping me out once again!

The workaround works perfectly for my usecase, and I understand (based on other similiar questions in here) that this likely imposes additional overhead as a result of the multiple roundtrips between V8 and .Net.

Just to clarify, does this make my assumption about the number being converted to a Single under the hood in ClearScript accurate? I assume this is being done so that it can be marshaled to the exposed host code (System.String.Format in my original example) - is this correct?

I'm just wanting to make sure that my understanding is clear, as I'm admittedly still a little confused if my observation/assumption isn't correct. Heck, if we're being honest, I'm still a bit confused either way but happy to have a workaround while investigating further...

If I am following the source correctly, the call sequence is essentially this:

ScriptEngine.Evaluate > V8ScriptEngine.Execute > V8ScriptEngine.ExecuteInternal > V8ScriptEngine.ExecuteRaw > V8ContextImpl::Execute

V8ContextImpl::Execute returns a V8Value to calling V8ScriptEngine instance, which bubbles back to ScriptEngine.Evaluate as System.Object. 

Once back into ScriptEngine.Evaluate with the response, V8ScriptEngine.MarshalToHost is called, which results in MiscHelpers.TryMarshalPrimitiveToHost being called - and since the type of 123123.75 is correctly inferred by .Net as a Double, MiscHelpers.MarshalDoubleToHost is called.

[MarshalDoubleToHost](https://github.com/microsoft/ClearScript/blob/041b5b4ca5395c5ba63ef7a4f3215d433074e941/ClearScript/Util/MiscHelpers.cs#L408) is where I get confused by the implementation... Consider the following:

![image](https://user-images.githubusercontent.com/361409/126383545-a3af2e95-5559-4e62-8488-290464ec018b.png)

Since Convert.ToSingle results in the local floatValue to be identical to the original value (e.g. 123123.75), the new 'down cast' [Single is returned](https://github.com/microsoft/ClearScript/blob/041b5b4ca5395c5ba63ef7a4f3215d433074e941/ClearScript/Util/MiscHelpers.cs#L431) vs the passed in Double - which is seemingly what .Net has issue with using correctly in String.Format(). But when a number is used that causes floatValue and value to not be equal (i.e. 123123.45, which result in floatValue=123123.453), [the originally passed in value type (Double) is passed back](https://github.com/microsoft/ClearScript/blob/041b5b4ca5395c5ba63ef7a4f3215d433074e941/ClearScript/Util/MiscHelpers.cs#L435) - which System.Format has no issues with.

I guess my question is "What's the reasoning behind down-casting a Double to a Single?"

Additionally, if you'd be willing to explain the intent behind MarshalDoubleToHost I would greatly appreciate it as I'm struggling to understand how it would reliably work - though I understand Github isn't intended to be a Q/A or support forum and you've already been more than helpful.

In any case, thanks again and keep up the awesome work!
-Matt

**Comment by ClearScriptLib** [comment]
Hi Matt,

Thank you very much for all your kind words!

>I understand Github isn't intended to be a Q/A or support forum

No worries! ClearScript is a side project – and a pet project – so we welcome any opportunity to discuss it.

>Just to clarify, does this make my assumption about the number being converted to a Single under the hood in ClearScript accurate?

Yes. On its way over from the script engine to the host, the number is narrowed from `double` to `float` (explanation below).

>I assume this is being done so that it can be marshaled to the exposed host code ... What's the reasoning behind down-casting a Double to a Single? ... if you'd be willing to explain the intent behind MarshalDoubleToHost ...

A number that moves from the script engine to the host is most often a method argument. It could also be a field or property value, or the result of some operation, but those are the simple cases. Method arguments are a very different story.

Because .NET methods can be overloaded and generic, selecting and/or constructing the correct method based on the call signature is a complicated endeavor for which ClearScript enlists the help of the C# Invoke Binder – a compiler component that's normally used at runtime to implement [`dynamic`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic) invocation.

For the binder to do its job, it needs the argument types. This presents a problem for numeric arguments. JavaScript numbers are all `double`, whereas .NET has a variety of numeric types. If ClearScript passed `double` arguments unmodified, all methods with numeric parameters of _narrower_ types would be excluded from consideration. For example, if `list` were an instance of `List<int>`, JavaScript syntax such as `list.Add(1)` would fail, since the `double` argument `1.0d` is [not implicitly convertible](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/numeric-conversions) to `int`.

Instead, ClearScript converts imported numbers to the narrowest representation that doesn't incur data loss. Doing so maximizes the probability of successful method binding because numbers _are_ implicitly convertible to _wider_ types. `MarshalDoubleToHost` is the method that performs this conversion.

However, you've provided the first known example of lossless narrowing leading to an undesired result. Therefore, the next ClearScript release will provide a way to disable this behavior, at least for floating-point numbers.

Thanks again!

**Comment by mattezell** [comment]
This makes more sense to me now - thank you for taking the time to provide the overview!

I look forward to continuing to work with the ClearScript project and watching how you all grow and evolve it.

Thanks again! Keep up the great work!
-Matt

**Comment by ClearScriptLib** [comment]
Reopening to track new API.

**Comment by ClearScriptLib** [comment]
[Version 7.1.5](https://github.com/microsoft/ClearScript/releases/tag/7.1.5) added [`ScriptEngine.DisableFloatNarrowing`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_DisableFloatNarrowing.htm).
