### ISSUE TITLE
Memory limits are not honored when using TypedArray API

### ISSUE THREAD

**Issue by SomebodyOdd** [microsoft/ClearScript#271]
ClearScript version: 7.1.4
Runtime: Windows 10 x64, .NET 5

It looks like TypedArray API flies under the radar when it comes both to V8 and ClearScript memory constraints settings.
For example, this code doesn't crash the process (at least when provided with enough available memory):
(WARNING: to make thing obvious this code consumes more than 4 GiB of memory)

```c#
static void Main(string[] args)
{
    var constraints = new V8RuntimeConstraints() { 
        MaxOldSpaceSize = 100,  //MiB
        MaxNewSpaceSize = 100,  //MiB

        //These properties are deprecated, but just in case
        MaxExecutableSize = 100, //MiB
        MaxYoungSpaceSize = 100  //MiB
    };
    var engine = new V8ScriptEngine(constraints)
    {
        MaxRuntimeHeapSize = (UIntPtr)(5 * 1024 * 1024), //5 MiB
        RuntimeHeapSizeSampleInterval = TimeSpan.FromMilliseconds(10)
    };

    engine.Execute("let arr = new Int8Array(4 * 1024 * 1024 * 1024); //4 GiB \n" +
        "for(let step = 0; step < arr.length; step++) arr[step] = step;");

    Console.WriteLine("I'm alive! I'm the Chosen One!\n");

    var heapUsage = engine.GetRuntimeHeapInfo();
    Console.WriteLine($"Heap size limit: {heapUsage.HeapSizeLimit / 1024d:N2} KiB");
    Console.WriteLine($"Total heap size: {heapUsage.TotalHeapSize / 1024d:N2} KiB");
    Console.WriteLine($"Total heap size executable: {heapUsage.TotalHeapSizeExecutable / 1024d:N2} KiB");
    Console.WriteLine($"Total physical size: {heapUsage.TotalPhysicalSize / 1024d:N2} KiB");
    Console.WriteLine($"Used heap size: {heapUsage.UsedHeapSize / 1024d:N2} KiB");
    Console.WriteLine($"Process private working set: {Process.GetCurrentProcess().WorkingSet64 / 1024d:N2} KiB");
}
```

and produces this output on my PC:
```
I'm alive! I'm the Chosen One!

Heap size limit: 299 008,00 KiB
Total heap size: 2 740,00 KiB
Total heap size executable: 256,00 KiB
Total physical size: 2 740,00 KiB
Used heap size: 805,70 KiB
Process private working set: 4 243 164,00 KiB
```

**Comment by ClearScriptLib** [comment]
Hi @SomebodyOdd,

The behavior you're seeing is correct. V8 allocates [array buffers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) outside the JavaScript heap. That's why heap size and usage end up so low compared to your array size. ClearScript's heap monitoring doesn't track array buffers either.

Thanks!

**Comment by SomebodyOdd** [comment]
Hi @ClearScriptLib,

Okay, is there any option to limit that as well? If not, maybe it's worth mentioning in the docs, somewhere around MaxRuntimeHeapSize and MaxOldSpaceSize properties?
I was looking for a way to run untrusted scripts with a resource limitation, but it looks like I can't (without some sort of external limits on a host process as a whole) because of this way of bypassing limits, right? Or maybe I missed something?

**Comment by ClearScriptLib** [comment]
Hi @SomebodyOdd,

>Okay, is there any option to limit that as well?

Not currently, but we could add a limit for the total array buffer memory allocated on behalf of a given V8 runtime. Would that suffice?

Cheers!

**Comment by SomebodyOdd** [comment]
> Would that suffice?

That would be perfect!
Is that gonna be a V8 limit (meaning, that a host process is doomed when this limit is crossed) or a ClearScript interruption-based limit?

A bit offtopic question: any advice on untrusted script execution? I don't mind interruptions or host process takedowns, but I do mind uncontrolled memory usage, which could put whole host OS in jeopardy. Of course, external tools for process limiting exist, but it's nice to have a first line of defense before falling back to a heavy guns =)

**Comment by ClearScriptLib** [comment]
Hi @SomebodyOdd,

>Is that gonna be a V8 limit (meaning, that a host process is doomed when this limit is crossed) or a ClearScript interruption-based limit?

V8 calls out to ClearScript to allocate and free array buffer memory, so ClearScript can enforce a limit without interruption. We've run some tests, and it appears that, if ClearScript fails to allocate array buffer memory, V8 currently throws a [`RangeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError) script exception, but as always with V8, that behavior could change.

>A bit offtopic question: any advice on untrusted script execution? I don't mind interruptions or host process takedowns, but I do mind uncontrolled memory usage, which could put whole host OS in jeopardy. Of course, external tools for process limiting exist, but it's nice to have a first line of defense before falling back to a heavy guns =)

Our understanding is that the most effective way to limit V8's heap memory usage is via [`MaxOldSpaceSize`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8RuntimeConstraints_MaxOldSpaceSize.htm), and we'll add a limit for array buffer memory. We aren't aware of any other off-heap allocation.

With all the settings currently available – plus the array buffer limit – additional monitoring really shouldn't be necessary. V8 is, after all, designed specifically for running untrusted code on the web, so if you're OK with the process disappearing, you should be all set. Since ClearScript 7.1.1, you can also use [`HeapExpansionMultiplier`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8RuntimeConstraints_HeapExpansionMultiplier.htm) in conjunction with [`MaxRuntimeHeapSize`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8ScriptEngine_MaxRuntimeHeapSize.htm) to minimize crashing. Our only other suggestion is that you avoid excessive CPU load by limiting how many V8 instances you run concurrently in a given process. A typical guideline is to use a "script engine pool" with a fixed size on the order of your CPU core count.

Good luck!

**Comment by SomebodyOdd** [comment]
> V8 calls out to ClearScript to allocate and free array buffer memory, so ClearScript can enforce a limit without interruption.

Sounds awesome!

Thanks a lot for your help!

**Comment by ClearScriptLib** [comment]
[Version 7.1.5](https://github.com/microsoft/ClearScript/releases/tag/7.1.5) added [`V8RuntimeConstraints.MaxArrayBufferAllocation`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8RuntimeConstraints_MaxArrayBufferAllocation.htm).
