### ISSUE TITLE
Remove a `minClientVersion` attribute from the `.nuspec` files

### ISSUE THREAD

**Issue by Taritsyn** [microsoft/ClearScript#272]
Hello!

Currently, all `.nuspec` files have an `minClientVersion` attribute with a value equal to 5.3, because of this, the NuGet packages cannot be installed by using old versions of Visual Studio.

As an example, you can see the [“Visual studio 2017 can't install JavaScriptEngineSwitcher.V8”](https://github.com/Taritsyn/BundleTransformer/issues/49) issue.

**Comment by ClearScriptLib** [comment]
Hi Andrey!

We specified NuGet 5.3 due to our required use of the `icon` attribute, but it looks like `icon` can be combined with `iconUrl` for backward compatibility.

However, since we're also required to use `license`, we need at least NuGet 4.9, which seems to be available for Visual Studio 2017.

So our current plan is to add `iconUrl` and lower the NuGet requirement to 4.9. Will that will be sufficient?

Thanks!

**Comment by Taritsyn** [comment]
> Will that will be sufficient?

I think that will be sufficient.

It's just that I don't use this attribute in my packages at all.

**Comment by ClearScriptLib** [comment]
Thanks, Andrey. We'll try something similar – including both `icon`+`iconUrl` and `license`+`licenseUrl` – and removing `minClientVersion`. Hopefully the packages will pass through all our internal checks in that form. Cheers!

**Comment by ClearScriptLib** [comment]
Ugh. Unfortunately NuGet doesn't allow `license`+`licenseUrl`. As company policy requires us to use `license` , we'll use `minClientVersion="4.9.0"` for correctness.

**Comment by Taritsyn** [comment]
I think this is also a good solution.

**Comment by ClearScriptLib** [comment]
[Version 7.1.5](https://github.com/microsoft/ClearScript/releases/tag/7.1.5) included this change.

**Comment by Taritsyn** [comment]
Thank you very much!
