### ISSUE TITLE
Question regarding V8ScriptEngine.Invoke()

### ISSUE THREAD

**Issue by mfe-** [microsoft/ClearScript#277]
Hi,

I'm playing around with `V8ScriptEngine.Invoke()` and encounterted the following with:

```
           v8ScriptEngine.Execute("function p(s) { Console.WriteLine(JSON.stringify(s)); Console.WriteLine(JSON.stringify(s.A)); }");
           var t = v8ScriptEngine.Invoke("p", new { A = new List<int>() {1,2,4,5 }  });
```
which results in the unexpected output `{}` and `[undefined]`. Trying something else like
```
            v8ScriptEngine.Execute("function p(l) {  Console.WriteLine(JSON.stringify(l)); }");
            var t = v8ScriptEngine.Invoke("p", new List<int>() { 1,2,3,4  });
```
...results in `[undefined]`. In my original starting code I used instead of a `List<int>` something like `List<MyClass>`. However it looks like that objects or instances containing properties of type `List<T>` `IEnumerables<T>` won't get serialized to the JavaScript part. Passing directly a `List<T>` to `v8ScriptEngine.Invoke()` also wont get serialized. 

The documentation https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Invoke.htm doesn't mention anything regarding this topic. What would be an acceptable workaround for this? Thanks in advanced.

**Comment by ClearScriptLib** [comment]
Hi @mfe-,

The issue here is unrelated to `ScriptEngine.Invoke`. It's just that that V8's implementation of `JSON.stringify` doesn't work with host objects. However, you can easily hook in a .NET JSON serializer. Here's an example that uses the popular [Json.NET](https://www.newtonsoft.com/json):

First, define a universal extension method that performs JSON serialization:

``` C#
// using Newtonsoft.Json;
public static class Extensions {
    public static string ToJson(this object obj) => JsonConvert.SerializeObject(obj);
}
```

Then, hook `JSON.stringify` to use your extension method:

``` C#
v8ScriptEngine.AddHostType(typeof(Extensions));
v8ScriptEngine.Execute(@"
    (function () {
        let stringify = JSON.stringify;
        JSON.stringify = (v, r, s) => v.ToJson?.() ?? stringify(v, r, s);
    })();
");
```

And now you'll get the behavior you're expecting. For example:

``` C#
v8ScriptEngine.AddHostType(typeof(Console));
v8ScriptEngine.Execute("function p(s) { Console.WriteLine(JSON.stringify(s)); }");
v8ScriptEngine.Invoke("p", new { A = new List<int> { 1, 2, 4, 5 } });
v8ScriptEngine.Execute("Console.WriteLine(JSON.stringify({foo: 123}))");
```

This code now emits the following output:

```
{"A":[1,2,4,5]}
{"foo":123}
```

Please let us know if you have additional questions or comments.

Thanks

**Comment by mfe-** [comment]
Thanks for your answer @ClearScriptLib which brought some helpful insights. I would like to ask one more question.

My main goal is to transform some existing "Linq predicates" to javascript and evaluate them with ClearScript.

My current setup:

```csharp
            v8ScriptEngine.AddHostType("Console", typeof(System.Console));
            v8ScriptEngine.AddHostType(typeof(Extensions));
            v8ScriptEngine.Execute(@"
    (function () {
        let stringify = JSON.stringify;
        JSON.stringify = (v, r, s) => v.ToJson?.() ?? stringify(v, r, s);
    })();
");
```

For example:

```csharp
           Item item = new Item() { Text = "foo", Details = new List<Item.Detail>() { new Item.Detail() { Name = "detail1" }, { new Item.Detail() { Name = "detail2" } } } };

            //works (result true expected)
            Predicate<Item> predicateText = new Predicate<Item>((i) => i.Text == "foo");
            var resultPredicate = predicateText.Invoke(item);
            v8ScriptEngine.Execute("function p(s) { return s.Text==\"foo\" }");
            var resultScript = v8ScriptEngine.Invoke("p", item);
            //works (result false expected)
            predicateText = new Predicate<Item>((i) => i.Text == "foo1");
            resultPredicate = predicateText.Invoke(item);
            v8ScriptEngine.Execute("function p(s) { return s.Text==\"foo1\" }");
            resultScript = v8ScriptEngine.Invoke("p", item);
```
This works like a charm as long as I do not deal with Lists<T>.

Consider the following example:

```csharp
            Predicate<List<Item.Detail>> predicateList = new Predicate<List<Item.Detail>>((i) => i.Any(a => a.Name == "detail1"));
            var resultPredicateList = predicateList.Invoke(item.Details);
            //v8 predicate works (result true expected)
            v8ScriptEngine.Execute("function p(s) { return s.some((s)=>s.Name==\"detail1\") }");
            resultScript = v8ScriptEngine.Invoke("p", item.Details); //throws a 'TypeError: s.some is not a function'
```
After investigating I encountered that `s` isn't a array and therefore the function some doesn't exist.

```csharp
                v8ScriptEngine.Execute("function p(s) { " +
                "var t = typeof s;" +
                "Console.WriteLine(t);" +
                "Console.WriteLine(JSON.stringify(t));" +
                "return true;" +
                "return s.some((s)=>s.Name!=\"detail1\") " +
                "}");
```
Outputs
`object` and `"object" `.

What do I need that v8ScriptEngine recognizes or translates a class with a property that `IEnumerable<T>` will be translated to a javascript array so that I'm able to use functions like `indexOf` or `some` and so on.

The ultimate goal is to translate the following Predicate to javascript an evaluate it with v8ScriptEngine.
`var predicate = new Predicate<Item>((i) => i.Text == "foo1" && !i.Details.Any(a=>a.Name=="detail1"));``

I tried to change the Type of Details from `List<Detail>` to `Detail[]` but the output was the same as before. Any help appreciated. Thanks in advanced.

**Comment by ClearScriptLib** [comment]
Hi @mfe-,

There are many ways to get the behavior you require.

>The ultimate goal is to translate the following Predicate to javascript and evaluate it with v8ScriptEngine.
`var predicate = new Predicate<Item>((i) => i.Text == "foo1" && !i.Details.Any(a=>a.Name=="detail1"));`

One approach might be simply to translate your predicate to JavaScript and work backwards from there. The most direct translation would look something like this:

``` JavaScript
let predicate = i => i.Text == 'foo1' && !i.Details.Any(a => a.Name == 'detail1');
```

That doesn't quite work, because [`Enumerable.Any`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any) requires a strongly typed delegate and therefore doesn't work with script functions. However, we can fix that by extending Linq with a script-friendly `Any` overload:

``` C#
public static partial class Extensions {
    public static bool Any<T>(this IEnumerable<T> source, dynamic predicate) {
        return source.Any(item => predicate(item));
    }
}
```

Now the JavaScript predicate works just like the C# version. Unfortunately you can't pass it directly into a method such as [`Enumerable.Where`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.where), but again we can fix that with a script-friendly extension:

``` C#
public static partial class Extensions {
    public static IEnumerable<T> Where<T>(this IEnumerable<T> source, dynamic predicate) {
        return source.Where(item => predicate(item));
    }
}
```

And now we can do things like this:

``` C#
v8ScriptEngine.AddHostType(typeof(Extensions));
v8ScriptEngine.AddHostType(typeof(Console));
v8ScriptEngine.AddHostObject("items", new List<Item> { ... });
v8ScriptEngine.Execute(@"
    let predicate = i => i.Text == 'foo1' && !i.Details.Any(a => a.Name == 'detail1');
    Console.WriteLine(items.Where(predicate).First().Details[0].Name);
");
```

On the other hand, you can work with JavaScript arrays if that's your preference. When you use `V8ScriptEngine`, .NET collections that you pass to JavaScript are [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols), so you can convert them to arrays simply by calling [`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from):

``` JavaScript
function p(s) {
    return Array.from(s).some((s)=>s.Name=='detail1');
}
```

Good luck, and please don't hesitate to send any additional questions our way!

**Comment by mfe-** [comment]
Thanks @ClearScriptLib 

I'll go with the Linq Extension approache as it looks like its slightly faster as the solution with `Array.from(s)`

|                            Method |          items       |     Mean |   Error |   StdDev |      Gen 0 |     Gen 1 | Allocated |
|---------------------------------- |--------------------- |---------:|--------:|---------:|-----------:|----------:|----------:|
|    PredicateWithAnyExtensionAsync |     Syste(...)] [67] | 216.2 ms | 4.09 ms |  4.55 ms | 13000.0000 |         - |     41 MB |
|         PredicateWithJsArrayAsync |     Syste(...)] [67] | 337.8 ms | 6.68 ms | 14.94 ms | 17000.0000 | 1000.0000 |     53 MB |
