### ISSUE TITLE
Interrupt() issue when using async/await in js

### ISSUE THREAD

**Issue by tony-xia** [microsoft/ClearScript#285]
Hi Team, i am having a weird issue. The engine execution cannot be interrupted. It seems the execution stops, but host does not get `ScriptInterruptedException` exception. Here is my code.
```cs
        static async Task Main()
        {
            using var engine = new V8ScriptEngine();

            Task.Run(async () =>
            {
                await Task.Delay(1000);
                engine.Interrupt();
            });

            engine.AddHostType(typeof(JavaScriptExtensions));
            engine.AddHostType(typeof(Console));
            engine.Script.GetInt = new Func<Task<int>>(GetInt);

            engine.Execute(@"
            async function f() {
                await GetInt().ToPromise();
                while(1) { Console.Write('.'); };
            }");

            try
            {
                await (engine.Script.f() as object).ToTask();
            }
            catch(ScriptInterruptedException)
            {
                Console.WriteLine("Interrupted");
            }
        }

        public static async Task<int> GetInt()
        {
            await Task.Delay(500);
            return 10;
        }
```

my csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ClearScript.Core" Version="7.1.5" />
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.1.5" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.1.5" />
  </ItemGroup>
</Project>
```

If I do one of the below changes, it can be interrupted successfully
1. Change `await GetInt().ToPromise();` to `GetInt().ToPromise();`
or 2. remove the line in GetInt() method. `await Task.Delay(500);`

Looking forward to your reply. thanks

**Comment by ClearScriptLib** [comment]
Hi @tony-xia,

Normally when an async function throws an exception, the JavaScript infrastructure intercepts it and uses it to reject the corresponding promise. That's the behavior your code expects.

The problem is that `ScriptEngine.Interrupt` does _not_ trigger a script exception that could be processed in that manner. Instead, it _aborts_ script execution and throws a .NET exception (`ScriptInterruptedException`) on the same thread.

In your case, that's a worker thread, and the exception is dropped on the floor. More importantly, the promise returned by `f` remains pending. So, although the script has been interrupted, your code can't get past the `await`.

Unfortunately, all of this is by design. `ScriptEngine.Interrupt` predates promises and async functions, and we're not aware of any newer, async-friendly V8 APIs for script interruption.

The changes you mentioned effectively turn `f` into a normal function. The `Console.Write` loop runs synchronously and is interrupted before the promise is created, triggering a `ScriptInterruptedException` on the calling thread.

As for a workaround, well, there's no way for the script engine to intercept script interruption – that's by design – but the _host_ can easily catch `ScriptInterruptedException`. If you run your interruptible code within a nested host layer, you can get close to the behavior you're looking for:

``` C#
engine.Script.NestedInvoke = new Action<dynamic>(func => func());
engine.Execute(@"
    async function f() {
        await GetInt().ToPromise();
        NestedInvoke(() => { while(1) { Console.Write('.'); }});
    }
");
try {
    await (engine.Script.f() as object).ToTask();
}
catch (ScriptEngineException e) when (e.GetBaseException() is ScriptInterruptedException) {
    Console.WriteLine("Interrupted");
}
```

Please send any additional thoughts our way.

Thanks!

**Comment by tony-xia** [comment]
thanks @ClearScriptLib  for your reply and the detail you provided. Now i understand a bit about what really happens under the hood. And i tried to interrupt engine when a c# method is being invoked, and found the engine continues the script after c# method.

```
        static async Task Main()
        {
            using var engine = new V8ScriptEngine();

            var task = Task.Run(async () =>
            {
                engine.AddHostType(typeof(JavaScriptExtensions));
                engine.AddHostType(typeof(Console));
                engine.Script.WaitForTwoSeconds = new Func<Task>(WaitForTwoSeconds);

                engine.Execute(@"
                async function f() {
                    await WaitForTwoSeconds();
                    Console.Write('This line will be executed.');
                }");

                try
                {
                    await (engine.Script.f() as object).ToTask();
                }
                catch(ScriptInterruptedException)
                {
                    Console.WriteLine("Interrupted");
                }
            });

            await Task.Delay(1000);
            engine.Interrupt();
            await Task.Delay(3000);
        }

        public static async Task WaitForTwoSeconds()
        {
            await Task.Delay(2000);
        }
```

The string "This line will be executed" will be printed.
looks like interruption has some problems when it comes with async  :(

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts or findings on this topic. Thank you!
