### ISSUE TITLE
Stop interacting with people using an anonymous account

### ISSUE THREAD

**Issue by SimonCropp** [Microsoft/ClearScript#31]
The use of @ClearScriptLib is detrimental in that it is nameless and faceless. The loss of the "feel of personal interaction" results in a feeling of either "talking to a bot" or dealing with a group of people who are actively trying to avoid proper engagement with the community. 

I am sure this was not your intent, but you may want to reconsider your reasons taking this approach

**Comment by ClearScriptLib** [comment]
Hi @SimonCropp,

We've used a team account since our first release on CodePlex nearly five years ago. The intent was to focus attention on the project and its users. To that end we've tried to be responsive to questions and receptive to feedback, and to address issues as quickly as possible.

This approach has been productive, with dozens of enhancements and fixes accumulated over the years, most of them inspired by interaction with the community. It doesn't always succeed, but it remains our preferred approach.

Thanks!
