### ISSUE TITLE
ModuleCategory.CommonJS changes behavior of engine.Evaluate

### ISSUE THREAD

**Issue by gjvdkamp** [microsoft/ClearScript#314]
Hi, it seems that adding ModuleCategory.CommonJS to an engine chnages the behavior of Evaluate, is this by design or a bug? 

See example below, I would expect both to return 100, but the second Evaluate returns 'undefined' instead of 100.
 
```
var code = "100"
dynamic res = engine.Evaluate(code); // returns 100
dynamic res2 = engine.Evaluate(new DocumentInfo() { Category = ModuleCategory.CommonJS }, code);  // returns undefined
dynamic res3 = engine.Evaluate(new DocumentInfo() { Category = ModuleCategory.Standard }, code); // returns 100
```

**Comment by ClearScriptLib** [comment]
Hi @gjvdkamp,

This behavior is by design.

ClearScript evaluates CommonJS module code within a function context. Your sample code ends up looking like this:

``` JavaScript
function (module, exports, require) {
    100
}
```

As each module system provides an official mechanism for exporting code and data, relying on the evaluation result shouldn't be necessary. Additionally, when a module is loaded via [`require`](http://wiki.commonjs.org/wiki/Modules/1.1.1#Require) or [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), the evaluation result isn't accessible.

Node.js does the [same thing](https://nodejs.org/api/modules.html#the-module-wrapper), by the way.

Good luck!

**Comment by gjvdkamp** [comment]
OK makes sense. Is there a way to get at the actual js code being evaluated to fully understand what it does?

**Comment by ClearScriptLib** [comment]
Hi @gjvdkamp,

>Is there a way to get at the actual js code being evaluated to fully understand what it does?

Once the module code is wrapped within a function as shown above, ClearScript evaluates the module simply by invoking the function, providing suitable arguments for `module`, `exports`, and `require`.

>Also, how should I interpret the ModuleCategory argument to the Evaluate statement? Does that refer to the Category of the script being evaluated or the module mechanism to apply?

If we understand your question correctly, the answer is _both_.

The `DocumentInfo.Category` property specifies what kind of document the host is asking ClearScript to evaluate. A normal script (`DocumentCategory.Script`) has the default capabilities supported by the script language. For JavaScript, that means a script that has no ability to interact with modules of any kind<sup>1</sup>.

A JavaScript module is a script that can exchange resources with other JavaScript modules of the same document category. CommonJS modules (`ModuleCategory.CommonJS`) use `require` and `exports` for this purpose, whereas standard (ES6) modules (`ModuleCategory.Standard`) use the `import` and `export` statements.

The API may be a bit confusing because ClearScript is designed to support multiple script languages. The document category is a language-agnostic concept, whereas CommonJS and ES6 modules are specific to JavaScript. That's why the JavaScript module categories, even though they're instances of the `DocumentCategory` class, are exposed by the separate class `JavaScript.ModuleCategory`.

Cheers!

<sup>1</sup>An exception is that normal JavaScript code can import ES6 modules via [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports), but that feature isn't yet standard and requires special enablement in ClearScript.

**Comment by gjvdkamp** [comment]
Thanks for the elaborate answer, much appreciated. Having the code be evaluated as an expression (or query) is quite valuable in our application of js. Think we'll try the typescript compiler on top of (raw) V8. Hope that leveraging its code generation/ module resolution functions will allow us to hit all design goals to make it feel just right. Need to do bit more figuring out to do for that. Thx so far you've been a great help.

**Comment by ClearScriptLib** [comment]
Hi @gjvdkamp,

>Having the code be evaluated as an expression (or query) is quite valuable in our application of js.

That's exactly what the `Evaluate` method is for. It's just that the expression can't be a module. Modules are designed to be evaluated only once in a given script engine instance, with their exports cached for subsequent access. Their evaluation results, when accessible, are unlikely to be useful.

If your expression depends on a library implemented by a module, you can easily make the library's exports accessible to normal scripts.

Good luck!

**Comment by ClearScriptLib** [comment]
Hi @gjvdkamp,

Just to give you a simple example, consider the following:

``` C#
engine.Execute(new DocumentInfo { Category = ModuleCategory.CommonJS }, "globalThis.require = require");
```

With this setup, normal scripts get access to CommonJS modules:

``` C#
Console.WriteLine(engine.Evaluate("require('Pythagoras').getHypotenuse(3, 4)"));
```

Here's the CommonJS module we used for this example:

``` JavaScript
// Pythagoras.js
exports.getHypotenuse = (a, b) => Math.sqrt(a**2 + b**2);
```

Please let us know if we can assist further.

Thanks!

**Comment by ClearScriptLib** [comment]
Please feel free to reopen this issue if you have additional questions on this topic. Thank you!

**Comment by gjvdkamp** [comment]
Yes pls close it you been a great help. Been distracted by more mundane issues lately will revisit this soon to give this a next try.

**Comment by gjvdkamp** [comment]
Hi all, 

I just made the switch 
from 
`object res = engine.Evaluate(JSCode);`
to 
`object res = engine.Evaluate(new DocumentInfo { Category = ModuleCategory.Standard },JSCode);`
This allows users to use the import statement to use modules. 

Trying this on older code does however reveil that code like 
x=5
that used to work fine before now gives a 'ReferenceError: x is not defined' error. 

Did setting the ModuleCategory put the engine in strict mode maybe? 
Any way to undo that? implicit variables just makes it easier to type code, most code is fine with global variables as there are only a few statements anyway.

**Comment by gjvdkamp** [comment]
Never mind I see it is a javascript spec thing, modules are always strict

**Comment by gjvdkamp** [comment]
But now any variable declared as 
var x = 5 
is no longer available in `engine.Script` or `engine.Global`, is that as expected? I though `var `should declare it as global or does strict mode affect that too?

Is there any way to list the variables in the engine when using `ModuleCategory.Standard`? It's user code so I wouldn't know the names in advance.

**Comment by ClearScriptLib** [comment]
hi @gjvdkamp,

>I though `var` should declare it as global or does strict mode affect that too?

The [`var`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var) statement declares global or function-scoped variables. However, CommonJS code is evaluated as a function body, and everything at the top level of a standard module is private unless explicitly exported.

Any kind of script can use [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) to access the [global object](https://developer.mozilla.org/en-US/docs/Glossary/Global_object), but modules were really designed to _prevent_ the behaviors you're looking for – side effects, implicit variable declaration, etc.

>Is there any way to list the variables in the engine when using `ModuleCategory.Standard`?

Inside a module, you can use `globalThis` to enumerate and assign global properties.

>It's user code so I wouldn't know the names in advance.

We're curious: How would you know what to do with properties you discover via enumeration? Are you just trying to list them for diagnostic purposes?

Anyway, perhaps modules aren't ideal for your scenario. It seems like you'd prefer classic non-strict behavior but with the additional ability to reuse libraries of some sort. If so, our best recommendation is to use a dummy CommonJS module to make ClearScript's `require` function available for non-module scripts. That technique is demonstrated [above](https://github.com/microsoft/ClearScript/issues/314#issuecomment-960137246).

Good luck!

**Comment by gjvdkamp** [comment]
Hmm no dice engine.Evaluate("globalThis") shows the same vars ar Script or Global, just this that were added to the enigine from C# but nothing declared in the js.. 

We use javascript as a 'sql for the web' making http calls to grab json data and transform those. Users can create the final result step by step, those intermediate variables and final result are shown in the right hand pane, code is on the left. Let me know if you want a demo some time. 

Now I just take engine.Script and enumerate what's in there but being able to use `import * from 'https://mymodule.js'` is pretty powerful obviously, then we can put often used code into modules and just call this, cleans it up quite a bit. But indeed I think i'll stick with the require approach then, have that now just thought import looked cooler, less 'hacky'. 

You're not aware of some black magic to let the js engine spill all the contents? Next step would be to try the debugging api, but there's nothing we can readily use there right? Would need to implement that from scratch?

**Comment by gjvdkamp** [comment]
Sorry only just read your idea how to enable require for non-module code, that hits the sweet spot. 

Evaluate works and it supports modules. Had a slight preference for the import syntax but I think we hit all the important goals this way. 

Thanks a lot!

**Comment by ClearScriptLib** [comment]
Hi @gjvdkamp,

>Had a slight preference for the import syntax

Unfortunately, the `import` statement is only available within standard modules, which are problematic in your case for the reasons we've discussed.

Another potential issue is that standard modules can be asynchronous, and if your user code imports an asynchronous module, it too becomes asynchronous, and that makes its return value inaccessible.

For these reasons it seems like a CommonJS-like, synchronous `require` function is a better solution.

Cheers!
