### ISSUE TITLE
Self-interrupting scripts don't interrupt cleanly.

### ISSUE THREAD

**Issue by SomebodyOdd** [microsoft/ClearScript#324]
Hello!

Suppose I have a script, that makes a call to host that results in a call to _V8ScriptEngine.Interrupt_ method (reason is arbitrary, but I can see how this could be used by script to interrupt itself through host call if something is really wrong).

Consider this code:
```c#
public class ScriptContext 
{
  private V8ScriptEngine _engine;

  public ScriptContext(V8ScriptEngine engine) => _engine = engine;

  public void Interrupt() => _engine.Interrupt();
  public void Ping() => Console.WriteLine("Ping!");
}

static void Main(string[] args) 
{
  var runtime = new V8Runtime();

  var engine = runtime.CreateScriptEngine();
  var context = new ScriptContext(engine);

  engine.AddRestrictedHostObject("context", context);

  var script = @ "<some script code I'll show in a bit>";

  try 
  {
    var evaluated = engine.Evaluate(script);
    Console.WriteLine($"Clean shutdown. Evaluated: {evaluated}");
  } 
  catch (ScriptInterruptedException) 
  {
    Console.WriteLine("Interrupted exception");
  } 
  catch (ScriptEngineException exc) 
  {
    Console.WriteLine($"Script exception: {exc.Message}");
  }
}
```

There are multiple problems which can occur here, depending on script. Here are some script examples:

### 1. Script appears to ignore the interruption request.
```js
context.Interrupt();
```
Output: `Clean shutdown. Evaluated: Microsoft.ClearScript.VoidResult`

### 2. Sneaky script result.
```js
context.Interrupt();
2 + 2;
```
Output: `Clean shutdown. Evaluated: 4`

### 3. Sneaky script error.
```js
context.Interrupt();
throw new Error('Gotcha!')
```
Output: `Script exception: Error: Gotcha!`

### 4. Host calls after interruption makes it right...
```js
context.Interrupt();
context.Ping();
```
Output: `Interrupted exception`

### 5. ...until it's not =)
```js
context.Interrupt();
try {
context.Ping();
}
catch(e) { }
```
Output: `Clean shutdown. Evaluated: [undefined]`

### 6. Some work without host calls is interrupted eventually
```js
context.Interrupt(); 
while(true) {}
```
Output: `Interrupted exception`

##

Can this be fixed somehow?
Ideally, script should be stopped immediately, never returning from _context.Interrupt_ method, even with an script-catchable exception, and _Evaluate_ method should throw _ScriptInterruptedException_, in all of the above cases. This leaves script runtime is somewhat known state.
Alternatively, if instant stopping of script is not possible, results and script errors should be ignored in favor of throwing _ScriptInterruptedException_, because that's what happened - script was interrupted by the script itself. This leaves script variables in an undefined state, meaning that further _Evaluate_ and _Execute_ (as well as accessing global variable with _Script_ property) could observe some changes, that script made between interruption request and interruption, but at least host gets to know that there was an interruption at all.

**Comment by ClearScriptLib** [comment]
Hi @SomebodyOdd,

>Ideally, script should be stopped immediately, never returning from _context.Interrupt_ method, even with an script-catchable exception, and Evaluate method should throw _ScriptInterruptedException_, in all of the above cases. This leaves script runtime is somewhat known state.

[`V8ScriptEngine.Interrupt`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_Interrupt.htm) is based on the only V8 API available for script interruption. That API, intended for cross-thread use, simply sets a flag that the script execution thread is supposed to check – _eventually_. As your test code demonstrates, that may not actually happen before the script exits normally.

>Alternatively, if instant stopping of script is not possible, results and script errors should be ignored in favor of throwing ScriptInterruptedException, because that's what happened - script was interrupted by the script itself. This leaves script variables in an undefined state, meaning that further Evaluate and Execute (as well as accessing global variable with Script property) could observe some changes, that script made between interruption request and interruption, but at least host gets to know that there was an interruption at all.

ClearScript _could_ do that, but as you say, the asynchronous nature of script interruption leaves script resources in an unpredictable state, making subsequent script execution tricky if not dangerous. V8 provides no _synchronous_ interruption facilities beyond normal JavaScript exceptions.

One thing you could do is mitigate the asynchrony by simply letting the script "spin" after invoking `V8ScriptEngine.Interrupt`. Unfortunately, invoking a spin function within `ScriptContext.Interrupt` wouldn't quite do the job. Since ClearScript doesn't propagate script interruption from nested script frames, the `ScriptInterruptedException` would be wrapped within a normal, catchable JavaScript exception in the outer script frame. However, you could fix that by replacing `ScriptContext.Interrupt` itself with a script function:

``` C#
public class ScriptContext {
    private V8ScriptEngine _engine;
    public ScriptContext(V8ScriptEngine engine) {
        _engine = engine;
        Interrupt = ((dynamic)_engine.Evaluate("engine => () => { engine.Interrupt(); while (true); }"))(engine);
    }
    public object Interrupt { get; }
    public void Ping() => Console.WriteLine("Ping!");
}
```

Please let us know if this works for you.

Thanks!

**Comment by SomebodyOdd** [comment]
> ClearScript could do that, but as you say, the asynchronous nature of script interruption leaves script resources in an unpredictable state, making subsequent script execution tricky if not dangerous.
Well, given what you said about V8 inner workings - it's in unpredictable state already, and always will be. But I think that doesn't imply that ClearScript should be unpredictable too =)
Maybe (if it's not to complicated to implement) ClearScript could detect these kind of situations where interruption was requested, but script halted earlier than it really happened and throw an exception to a script caller, making it's behavior deterministic in that regard?
But, on the other hand, it's technically a breaking change...

**Comment by ClearScriptLib** [comment]
Hi @SomebodyOdd,

>Maybe (if it's not to complicated to implement) ClearScript could detect these kind of situations where interruption was requested, but script halted earlier than it really happened and throw an exception to a script caller, making it's behavior deterministic in that regard?

We could guarantee an exception only when `Interrupt` is called on the script execution thread – what you're calling the "self-interrupting script" scenario – because otherwise there's an unavoidable race between script execution and interruption.

But even for self-interrupting scripts, this solution would be _worse_ than spinning, because any other script execution after `Interrupt` could leave your application in an unknown state. In fact, as far as we can tell, spinning after `Interrupt` provides the ideal behavior you described in your original message.

Have you had a chance to try the code change we proposed above?

Thanks!

**Comment by ClearScriptLib** [comment]
[Version 7.2.1](https://github.com/microsoft/ClearScript/releases/tag/7.2.1) added support for interrupt [propagation](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8ScriptEngine_EnableRuntimeInterruptPropagation.htm) and [cancellation](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_CancelInterrupt.htm).
