### ISSUE TITLE
CPU Profiling with Chrome DevTools for Node.js (ClearScript V8)

### ISSUE THREAD

**Issue by tombatron** [microsoft/ClearScript#327]
Hi there!

We're experimenting with using ClearScript V8 to "server side render" React components. Do you have any guidance for loading and executing these components such that the CPU profiling results could be used to detect hotspots within our React components?

Thus far we've been able to attach the Chrome Node.js tools to a running instance and all of the source mapping and what not seems to work. But when running the CPU profiler, only `(program)` appears in the results. 

Thanks!

Tom

**Comment by ClearScriptLib** [comment]
Hi Tom,

>Do you have any guidance for loading and executing these components such that the CPU profiling results could be used to detect hotspots within our React components?

ClearScript provides CPU profiling support in the form of [start](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_V8_V8ScriptEngine_BeginCpuProfile.htm)/[stop ](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_EndCpuProfile.htm)APIs that the host invokes to produce a JSON-formatted file that can be opened in Chrome/Edge DevTools to visualize the profile.

>But when running the CPU profiler, only `(program)` appears in the results.

Please clarify. How are you invoking the CPU profiler? Where are you seeing the results? Finally, what are you expecting to see?

Thanks!

**Comment by tombatron** [comment]
Hi there!

> How are you invoking the CPU profiler?

Assuming the engine is configured to have the debug port listening on port 9229. 

1. From within Chrome I open the "Inspect" panel by visiting: chrome://inspect
2. Once that panel is open I click on the link labeled: `Open dedicated DevTools for Node`
3. Once the application is running it will appear like so:

![image](https://user-images.githubusercontent.com/119369/145088696-501024e0-a2ca-4b9c-b1f8-042331867997.png)

> Where are you seeing the results?

Once the application is running and the debugger is attached I start the CPU profiler by clicking the "record" button :

![image](https://user-images.githubusercontent.com/119369/145089119-24daa484-de4e-4504-bdfc-ae2d897c8c87.png)

Which when stopped (by clicking the "record" button once more) the results are as displayed above. It's important to note, that while the profiler is running I am exercising the application such that JavaScript instructions are being sent to ClearScript. 

> Finally, what are you expecting to see?

At the very least I'd expect to a call to `ReactDOMServer.renderToString(...` in there somewhere.

**Comment by ClearScriptLib** [comment]
Hi @tombatron,

We've reproduced this issue and are investigating.

Thanks!

**Comment by ClearScriptLib** [comment]
Hi @tombatron,

The problem here is that V8 only collects profile data on the thread that started the profile.

That limitation is not a problem for Chromium or Node.js. Those environments are based on the event loop model, which ensures that a V8 runtime always executes code and handles debugger commands on the same thread.

ClearScript, on the other hand, is designed to accommodate _any_ application architecture, so it doesn't impose any particular threading model upon the host. It is our assumption that script code execution is an ancillary feature rather than the host's primary functionality. Requiring an event loop would make ClearScript integration much more involved and disruptive.

Unlike Chromium and Node.js, ClearScript doesn't reserve threads for V8 operations. Instead, it executes script code on the caller's thread and handles debugger commands on worker threads. This works perfectly well for most debugger commands, but when ClearScript receives a "start profiling" command, it has no way to predict what thread will end up running the code to be profiled. 

Unfortunately, that means that debugger-initiated CPU profiling is unlikely to work with ClearScript.

Sorry!

**Comment by tombatron** [comment]
Fair enough. 

Does this mean that leveraging the {Begin|Collect|End}CpuProfile methods should yield results closer to what we're looking for, versus having the external debugger initiate?

**Comment by ClearScriptLib** [comment]
>Does this mean that leveraging the {Begin|Collect|End}CpuProfile methods should yield results closer to what we're looking for, versus having the external debugger initiate?

Yes. If you call [`BeginCpuProfile`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_BeginCpuProfile_1.htm) on the thread that will execute the code you wish to profile, [`EndCpuProfile`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_EndCpuProfile.htm) should return useful data. You can then use [`ToJson`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8CpuProfile_ToJson.htm) to produce a file-based profile that can be loaded into DevTools for visualization.

**Comment by tombatron** [comment]
Thank you so much for the effort here!
