### ISSUE TITLE
Returning native Javascript objects from CLR

### ISSUE THREAD

**Issue by jsobell** [Microsoft/ClearScript#37]
I have a situation where a registered library (e.g. `AddHostObject("utils", new Utils())`) has a function that returns an object based on a set of parameters.  All is fine, so long as the type is a core system type marshalled to number, string, boolean etc, but if the return type is a DateTime object things get very messy.
I can modify my external call to return a long number, and require the user always wrap it in a `Date(blah)`, but this is messy and unintuitive for users:
`var x = utils.GetDate('tomorrow').getDay()`
has to be coded as
`var x = new Date(utils.GetDate('tomorrow')).getDay()`

Looking at the returned types, the DotNet DateTime is returned as a HostObject, but a Javascript `Date` object is a V8ScriptItem.
Is there any way to have the result of a CLR function return a javascript Date object? I can't wrap the call in the expression because it may be used in the middle of another expression (e.g.
``console.log(`Hi Dave, I can't do that until ${utils.GetDate('tomorrow').toLocalString()}`)``

**Comment by ClearScriptLib** [comment]
Hi @jsobell,

> Is there any way to have the result of a CLR function return a javascript Date object?

Sure. The host can invoke the script engine to create a script object. Here's a sample partial implementation of `Utils` that demonstrates this:

``` C#
public class Utils {
    private readonly object _createJsDate;
    public Utils(ScriptEngine engine) {
        _createJsDate = engine.Evaluate(@"
            (function (yr, mo, day, hr, min, sec, ms) {
                return new Date(yr, mo, day, hr, min, sec, ms);
            }).valueOf()
        ");
    }
    private object CreateJsDate(DateTime dt) {
        return ((dynamic)_createJsDate)(
            dt.Year, dt.Month - 1, dt.Day,
            dt.Hour, dt.Minute, dt.Second, dt.Millisecond
        );
    }
    private static DateTime GetDateTime(string desc) {
        return DateTime.Now;
    }
    public object GetDate(string desc) {
        return CreateJsDate(GetDateTime(desc));
    }
}
```

Good luck!

**Comment by jsobell** [comment]
Thanks, that's great. I didn't realise you could return a function and call it explicitly like that!

I've come to the conclusion that mixing CLR DateTime and JS Date is simply a no-go situation.
An evaluation such as `[ new Date(), DateTime.Now ]` returns a javascript array of a Date object and a ScriptHost, and trying the return this in any meaningful manner is almost impossible.
For most functions I stringify the result, but `JSON.stringify([ new Date(), DateTime.Now ])` simply returns `null` for the DateTime object.
Likewise passing in DateTime to functions. Without any native marshalling of the DateTime structure, an expression such as
`DateTime.Now.toString()` breaks, as it's trying to apply a javascript method to a DateTime object, and I can't see any way to intercept the functionality and implement my own marshalling.
Is it feasible to add marshalling to the underlying engine? `Date()` is the primary object-related pseudo-native datatype in javascript that is commonly flicked back and forth between the CLR and the engine, so not having to jump through hoops to handle them would be wonderful.

**Comment by ClearScriptLib** [comment]
Hi @jsobell,

Because ClearScript's primary aim is to provide full access to .NET features, it performs automatic data conversion only when it would be too painful to use otherwise, such as when dealing with fundamental values (numbers, strings, Booleans).

Date-time values are an interesting case. In some applications they're as fundamental as integers, but platforms and script engines vary wildly in terms of date-time representation and capabilities. Automatic conversion would almost always be lossy.

The sample above demonstrates how you might expose a .NET method that returns a JavaScript `Date`, but you're right, a nontrivial .NET API that dealt extensively with `System.DateTime` could be difficult to wrap or retrofit for direct `Date` support.

ClearScript's marshaling happens in several stages, and not all in managed code, so it would probably be easier to modify it for `Date` support than to make it generally extensible. It might make sense to make automatic date-time conversion something you can opt into. We'll take a look.

In the meantime, one other possibility is to leverage ClearScript's support for [extension methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods). Consider something like this:

``` C#
public static class ScriptExtensions {
    public static object toJsDate(this DateTime dt) {
        return ToJsDate(dt, ScriptEngine.Current);
    }
    private static object ToJsDate(DateTime dt, ScriptEngine engine) {
        object createDate = engine.Script.__createDate;
        if (createDate is Undefined) {
            createDate = engine.Evaluate(@"
                __createDate = function (yr, mo, day, hr, min, sec, ms) {
                    return new Date(yr, mo, day, hr, min, sec, ms);
                };
            ");
        }
        return ((dynamic)createDate)(
            dt.Year, dt.Month - 1, dt.Day,
            dt.Hour, dt.Minute, dt.Second, dt.Millisecond
        );
    }
}
```

And then:

``` C#
engine.AddHostType(typeof(Console));
engine.AddHostType(typeof(DateTime));
engine.AddHostType(typeof(ScriptExtensions));
engine.Execute("Console.WriteLine(JSON.stringify([ new Date(), DateTime.Now.toJsDate() ]))");
```

And of course you could add a reverse conversion method to the `Date` prototype for passing date-times to your managed API. It isn't a painless approach, but it might be workable.

Cheers!

**Comment by ClearScriptLib** [comment]
[Version 5.5.2](https://github.com/Microsoft/ClearScript/releases/tag/5.5.2) supports optional date-time conversion.
