### ISSUE TITLE
I cannot assign the c# Array or List to javascript, can you provide the Class to help set Array value to JS

### ISSUE THREAD

**Issue by feiyin0719** [microsoft/ClearScript#375]
When I assign the c# Array or List to JS, when I use the forEach in JS, it will report error, I think we need a class corresponding to JS array to help us easily pass arrays to JS.
Now I set the array to JS like this
```
public object CreateNativeArray<T>(List<T> data) {
            SetValue("__$_convert_array_data__", new JSIList<T>(data));
            var obj = Evaluate("var array = [];__$_convert_array_data__.forEach(t=>{array.push(t);});array;");
            
            return obj;
        }
```

**Comment by ClearScriptLib** [comment]
Hi @feiyin0719,

>When I assign the c# Array or List to JS, when I use the forEach in JS, it will report error

That's correct. Instead of converting them, ClearScript prefers to give the script engine full access to host objects. The problem with conversion is that it's both costly and lossy.

Still, if you're using V8, there are convenient ways to do what you need. Consider this example:

``` C#
engine.AddHostType(typeof(Console));
var myArray = new[] { 5, 4, 3, 2, 1 };
```

Managed arrays support [JavaScript iteration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols), so script code can easily use them without conversion:

``` C#
engine.Script.myArray = myArray;
engine.Execute("for (var item of myArray) Console.WriteLine(item)");
```

If you _must_ convert a managed array to a script array, you can do it very easily:

``` C#
engine.Script.myArray = engine.Script.Array.from(myArray);
engine.Execute("myArray.forEach(item => Console.WriteLine(item))");
```

Cheers!

**Comment by feiyin0719** [comment]
ok, I will try it, thanks
