### ISSUE TITLE
Passing V8Array to C# Method

### ISSUE THREAD

**Issue by burakoner** [microsoft/ClearScript#383]
Hi,

I'm working on a custom trading indicator scripting over ClearScript. I have a TechnicalAnalysis C# Class and there are many indicators. I want to pass ClearScript(Javascript) variables to my TechnicalAnalysis C# Class. If I send main data from C# side there is no problem. Because I can send List<...> data to javascript and when I need to analyze it I can call C# method inside javascript. Everything is perfect.

But If I create data in javascript side I cant pass this variables into C# side.

Let me show you an example. This is only one indicator in my TechnicalAnalysis  Class.

```C#
public List<decimal?> sma(IEnumerable<Kline> klines, int periods, CandlePart candlePart = CandlePart.Close)
    => klines.OrderBy(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
public List<decimal?> sma(IEnumerable<decimal> values, int periods, CandlePart candlePart = CandlePart.Close)
    => Kline.Import(values).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
public List<decimal?> sma(IEnumerable<decimal?> values, int periods, CandlePart candlePart = CandlePart.Close)
    => Kline.Import(values).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
public List<decimal?> sma(IEnumerable<double> values, int periods, CandlePart candlePart = CandlePart.Close)
    => Kline.Import(values).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
public List<decimal?> sma(IEnumerable<double?> values, int periods, CandlePart candlePart = CandlePart.Close)
    => Kline.Import(values).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
public List<decimal?> sma(IEnumerable<float> values, int periods, CandlePart candlePart = CandlePart.Close)
    => Kline.Import(values).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
public List<decimal?> sma(IEnumerable<float?> values, int periods, CandlePart candlePart = CandlePart.Close)
    => Kline.Import(values).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
```
And this is working Javascript Code
```JS
var k = data.GetKlines('MARKETSYMBOL','1D');
var sma = ta.sma(k, 20);
for(var i=0; i<sma.Count; i++){
    Console.WriteLine('SMA['+ i +']: ' + sma[i]);
}
```

But when I create data inside javascript as below it doesnt work

```JS
var numbers = [1,2,3,4,5,5,6,7,9,10];
var smanumbers = ta.sma(numbers, 3);
```

I debugged and found type of "numbers" variable in javascript, passes as `Microsoft.ClearScript.V8.V8ScriptItem.V8Array` and I cant write an overriding method because it is private class.

I also inspected https://github.com/microsoft/ClearScript/issues/178 issue but the main difference with me and that issue is I have to pass this variables as parameter, but in that issue it is a return type.

I couldn't solve this problem. Do you have a solution?

**Comment by ClearScriptLib** [comment]
Hi @burakoner,

>I couldn't solve this problem. Do you have a solution?

`V8Array` implements [`IList`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist), which you could use to examine the array from the .NET side. However, `IList`, like a JavaScript array, isn't strongly typed, so you'd have to convert each element explicitly and figure out what to do with non-homogeneous arrays. With `IList` you'd also have to make lots of expensive calls into the script engine – at least one per element.

Instead, consider using a JavaScript [typed array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays). On the .NET side, a typed array implements [`ITypedArray`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_JavaScript_ITypedArray_1.htm) and can be converted to a .NET collection in just one round trip to the script engine.

Here's a simple example. First, add an overload or extension method that works with `ITypedArray`:

``` C#
public List<decimal?> sma(ITypedArray<double> values, int periods, CandlePart candlePart = CandlePart.Close)
    => sma(values.ToArray(), periods, candlePart);
```

Now you have an easy way to pass in data from JavaScript:

``` JavaScript
var numbers = [1,2,3,4,5,5,6,7,9,10];
var smanumbers = ta.sma(new Float64Array(numbers), 3);
```

Good luck!

**Comment by burakoner** [comment]
Yes it works. But I cant use this solution. Because as I said before this scripting system is not for my own usage. It will be public. I cant explain end users that they need to use Float64Array class.

I found another way. I merged all overloaded method into one which accepts dynamic parameter for data. I'm checking type of dynamic data and do calculation. 

```C#
public List<decimal?> sma(dynamic data, int periods, CandlePart candlePart = CandlePart.Close)
{
    if (data is IEnumerable<Kline> klines)
        return klines.OrderBy(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
    else if (data is IEnumerable<decimal> n01)
        return Kline.Import(n01).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
    else if (data is IEnumerable<decimal?> n02)
        return Kline.Import(n02).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
    else if (data is IEnumerable<double> n03)
        return Kline.Import(n03).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
    else if (data is IEnumerable<double?> n04)
        return Kline.Import(n04).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
    else if (data is IEnumerable<float> n05)
        return Kline.Import(n05).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
    else if (data is IEnumerable<float?> n06)
        return Kline.Import(n06).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
    else
        return Kline.Import((List<double?>)TH.FromV8Array(data)).OrderByDescending(x => x.CloseTime).GetSma(periods, candlePart).Select(x => x.Sma).Reverse().ToList();
}
```

And here is FromV8ArrayMethod
```C#
public static List<double?> FromV8Array(dynamic data)
{
    try
    {
        var v8data = ((IList)data);
        if (v8data.Count > 0)
        {
            var list = new List<double?>();
            foreach (var item in v8data)
            {
                if (item == null) list.Add(null);
                if (item is byte v01) list.Add(Convert.ToDouble(v01));
                if (item is sbyte v02) list.Add(Convert.ToDouble(v02));
                if (item is short v03) list.Add(Convert.ToDouble(v03));
                if (item is ushort v04) list.Add(Convert.ToDouble(v04));
                if (item is int v05) list.Add(Convert.ToDouble(v05));
                if (item is uint v06) list.Add(Convert.ToDouble(v06));
                if (item is long v07) list.Add(Convert.ToDouble(v07));
                if (item is ulong v08) list.Add(Convert.ToDouble(v08));
                if (item is float v09) list.Add(Convert.ToDouble(v09));
                if (item is double v10) list.Add(Convert.ToDouble(v10));
                if (item is decimal v11) list.Add(Convert.ToDouble(v11));
            }
            return list;
        }
    }
    catch { }

    // Return
    return new List<double?>();
}
```

But I still believe this issue is a problem for ClearScript and you need to think about a real solution.

**Comment by ClearScriptLib** [comment]
Hi @burakoner,

>I cant explain end users that they need to use Float64Array class.

Why not? Aren't you providing documentation for your API? Besides, there's nothing unusual about typed arrays; they're standard JavaScript and trivially convertible to and from plain arrays.

If you wish to support plain arrays directly, you can simply add an overload that takes `IList` or [`ScriptObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptObject.htm). You can even expose a JavaScript method that converts arrays to `Float64Array` (or some other representation) before jumping over to .NET. You have lots of options here.

>I merged all overloaded method into one which accepts dynamic parameter for data. I'm checking type of dynamic data and do calculation.

Why merge when ClearScript supports overloads? Also, consider using `IList` or `ScriptObject` instead of `dynamic`. Each `dynamic` code site incurs significant runtime overhead.

>And here is FromV8ArrayMethod

Again, performance is a potential issue here, as you're retrieving JavaScript array elements one by one.

>But I still believe this issue is a problem for ClearScript and you need to think about a real solution.

Please clarify the problem as you see it – or what your ideal behavior would be. Hopefully we've shown that ClearScript gives you many options for exposing the API and behavior you require, but we're always looking for suggestions.

One thing we try to avoid is automatic data conversion. JavaScript and .NET type systems are radically different, and automatic data conversion tends to be application-specific and lossy. There are exceptions – such as numeric, date/time, and task/promise conversions – that are lossless and/or universally useful, and ClearScript provides optional support for those.

Thanks!

**Comment by burakoner** [comment]
The performance is really very important in my project. Now, an average script (around 50 lines) execution duration is about 200-300 milliseconds. This is very far away from my goal. But, when I need to make a decision between simplicity and performance I have to choose simplicity for end users. 

Anyway. I tried both IList and ScriptObject overloads. ScriptObject works fine, but I still get exception for IList method. Both methods are exception is below. Please keep in mind I tried them one by one. After I tried ScriptObject method, I deleted that method codes and tried for second one.


![Screenshot_8](https://user-images.githubusercontent.com/21169085/171149463-4b34954d-3ef0-4c63-a279-be67d13f96b1.png)

![Screenshot_7](https://user-images.githubusercontent.com/21169085/171149501-e95bf1b6-fd57-4098-9ee8-ce6d2bc37f06.png)

![Screenshot_6](https://user-images.githubusercontent.com/21169085/171149527-f5486995-3e58-4981-84fc-dffbc5390efe.png)

Thanks for your help

**Comment by ClearScriptLib** [comment]
Hi @burakoner,

>when I need to make a decision between simplicity and performance I have to choose simplicity for end users

Of course, and we aim to make ClearScript flexible enough to let you provide both.

Normal arrays are simple but slow to access form .NET. They're untyped, and they don't provide bulk access to their contents. Typed arrays have the performance, but they aren't quite as simple.

However, nothing stops your API from accepting normal arrays as input but using typed arrays under the covers. Please see the example below.

>I still get exception for IList method.

Plain JavaScript arrays are untyped, so they implement `IList` rather than `IList<T>`. Try something like this:

``` C#
public List<double> dummy(IList values, int periods) {
    var constructor = (ScriptObject)ScriptEngine.Current.Script.Float64Array;
    var typedArray = (ITypedArray<double>)constructor.Invoke(true, values);
    return typedArray.ToArray().Select(value => value * periods).ToList();
}
```

That's just one way to do it, of course. Instead of the `Float64Array` constructor, you could invoke a custom conversion function that follows the rules of your choice – e.g., for dealing with invalid data, etc.

Good luck!

**Comment by burakoner** [comment]
Yesssss

```C#
public List<double> dummy(IList values, int periods)
```
This method works perfectly. Thanks a lot.

**Comment by hyzx86** [comment]
Hi @ClearScriptLib ， I have a similar requirement, but I want to pass an array object, not an array of scalar values

I was wondering is there any way to parse this into a collection of dictionaries without relying on the ClearScript package?

In this case, I wanted a script to build up a collection of objects, and then my ORM framework could convert dictionary types into SQL Insert statements
![image](https://user-images.githubusercontent.com/15613121/218530183-f1ae5803-3215-4bca-b6ae-92567bf98cab.png)

Thanks!

**Comment by ClearScriptLib** [comment]
Hi @hyzx86,

>I wanted to pass an **array object** instead of an array of scalar values

Just to be clear, by "array object", do you mean a JavaScript array whose elements are JavaScript objects?

>parse this into a collection of dictionaries **without relying on the ClearScript package**?

Again, just to be clear, do you mean that you prefer not to use ClearScript types such as [`ScriptObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptObject.htm)?

Thanks!

**Comment by hyzx86** [comment]
Hi @ClearScriptLib 

> > I wanted to pass an **array object** instead of an array of scalar values

> Just to be clear, by "array object", do you mean a JavaScript array whose elements are JavaScript objects?

Yes,this my script 

``` js 

var data = Array.from(readExcel({
    Source: {
        FilePath: "/data.xlsx",
        StreamSource: "FileStore"
    }
}))

/** excel data content sample 
[
    {      
      "EmplID": "xxx",
      "SaleName": "xxx",
      "MgrID": "xxx",
      "LineManager": "xxx",
      "isDelete": 0,
      "isApprover": 1,
      "Remark": null
    },

 */ 
// return  Array.isArray(data) //true
// return data.toString()//[object Object],[object Object],[object Object],[object Object]
 
var tableData = data.map(x => {
    var obj = {}
    for (key in x) {
        if (key != "Id" && x.hasOwnProperty(key)) {
            obj[key] = x[key]
        }
    }
    return obj
})

// return tableData[0];
/* value of tableData[0]
 {
    "GetType": {}, 
    "ToString": {},
    "Equals": {},
    "GetHashCode": {},
//The four fields above cannot be excluded with hasOwnProperty?

    "EmplID": "xx",
    "SaleName": "x",
    "MgrID": "xx",
    "LineManager": "xx",
    "isDelete": 0,
    "isApprover": 1,
    "Remark": null
  }
]
*/
//return tableData.toString()//[object Object],[object Object],[object Object],[object Object],[object Object]...

//create a dotnet instance
var db = useDb("mydb"); 
// db.ExecuteNonQuery("truncate table SaleWithLineManager")
// call function ExternalDbProvider.Insert(string, object, ExecuteOptions excuteOptions = null)
var total = db.Insert("SaleWithLineManager", tableData)

return {
    total
};
```

The script will be executed here

```C# 

            var engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging | V8ScriptEngineFlags.EnableDateTimeConversion);

            var methods = scriptingManager.GlobalMethodProviders.SelectMany(x => x.GetMethods());
            if (extraMethods != null)
            {
                methods = methods.Concat(extraMethods);
            }
            foreach (var method in methods)
            {
                engine.Script[method.Name] = method.Method(serviceProvider);
            }
         var jsValue = engine.Evaluate(@"(function () { " + script + "\r\n})() ");
```


Here you can see that the js functions of all dotnet extensions come from a set of dependency injection,
That's why I wish I could define C# functions without relying on 'ClearScript' directly.

Before use `ClearScript`, they were js functions used to extend Jint


In ExternalDbProvider

```C#
    public class ExternalDbProvider
  {
        public object Insert(string tableName, object[] obj, ExecuteOptions executeOptions = null)
        {
            return InsertList(tableName, obj, executeOptions);
        }
        public object Insert(string tableName, object obj, ExecuteOptions executeOptions = null)
        {
            if (obj is IList list)
            {
                return InsertList(tableName, list, executeOptions);
            }

            return InsertList(tableName, new[] { obj }, executeOptions);
        }

        
        private object InsertList(string tableName, IList list, ExecuteOptions executeOptions = null)
        {
            //var dictList = (list as IDictionary<string, object>[]).ToDictionary();
            var dictList = new List<Dictionary<string, object>>();
            for (int i = 0; i < list.Count; i++)
            {
                var item = list[i];
                var refl = (item as IReflect);
                var properties = refl.GetFields(BindingFlags.Public);
                var dict = properties.ToDictionary(k => k.Name, v => v.GetValue(item));
                dictList.Add(dict);
            }

            return InternalInsert(tableName, executeOptions, dictList);

        }

        private object InternalInsert(string tableName, ExecuteOptions executeOptions, IEnumerable<Dictionary<string, object>> dictList)
        {
            if (dictList.Count() > 0)
            {
                var insert = FreeSql.InsertDict(dictList).AsTable(tableName);
                if (executeOptions != null)
                {
                    if (executeOptions.NoneParameter)
                        insert.NoneParameter();
                    if (executeOptions.ToSql)
                        return insert.ToSql();
                }

                try
                {
                    return insert.ExecuteAffrows();
                }
                catch (Exception ex)
                {
                    _logger.LogError("Debug:{sql}，error:{error}", insert.ToSql(), ex);
                    //throw ex;
                    return 0;
                }
            }
            else
            {
                return 0;
            }
        }
}
```
At the beginning, I wanted it to differentiate method calls based on C# 's function overloading feature
```
public object Insert(string tableName, object[] obj, ExecuteOptions executeOptions = null)
```
and 
```
public object Insert(string tableName, object obj, ExecuteOptions executeOptions = null)
```

But in practice, the following script always hits the latter

```
db.Insert("SaleWithLineManager", [{aaa:123},{aaa:222}])
```
I checked the type of the input parameter, which is an instance of the V8Array type
So, I used the following code to parse it

``` C#        
        private object InsertList(string tableName, IList list, ExecuteOptions executeOptions = null)
        {
            //var dictList = (list as IDictionary<string, object>[]).ToDictionary();
            var dictList = new List<Dictionary<string, object>>();
            for (int i = 0; i < list.Count; i++)
            {
                var item = list[i];
                var refl = (item as IReflect);
                var properties = refl.GetFields(BindingFlags.Public);
                var dict = properties.ToDictionary(k => k.Name, v => v.GetValue(item));
                dictList.Add(dict);
            }
            return InternalInsert(tableName, executeOptions, dictList);
        }
```



I have now finished parsing the `V8Array` ，Is there a better way to parse the V8Array type?

**Comment by ClearScriptLib** [comment]
Hi @hyzx86,

>Is there a better way to parse the V8Array type?

As you've seen, JavaScript arrays currently implement [`IList`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ilist) on the .NET side, whereas generic JavaScript objects – e.g., `{foo:123,bar:456}` – are fully accessible via [`ScriptObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptObject.htm) or [`IJavaScriptObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_JavaScript_IJavaScriptObject.htm).

If you prefer not to use ClearScript API elements, your options are currently [`DynamicObject`](https://learn.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject), [`IDynamicMetaObjectProvider`](https://learn.microsoft.com/en-us/dotnet/api/system.dynamic.idynamicmetaobjectprovider), [`IReflect`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.ireflect), and [`IExpando`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.expando.iexpando) (the latter on .NET Framework only). You can also make use of the [`dynamic`](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic) infrastructure.

For example, the following might be slightly more convenient than the above:

``` C#
foreach (var item in list) {
    var names = ((DynamicObject)item).GetDynamicMemberNames();
    dictList.Add(names.ToDictionary(name => name, name => ((dynamic)item)[name]));
}
```

In any case, it's likely that Jint and ClearScript expose script objects differently, so writing code specifically for one or the other is likely necessary. If so, then we aren't clear on why you're avoiding ClearScript's API.

Also, we're currently evaluating making V8 non-array JavaScript objects implement [`IDictionary<string, object>`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2) in the next release. However, arrays will still implement `IList` or [`IList<object>`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ilist-1) (as opposed to `IList<IDictionary<string, object>>`), because they can hold primitive values as well as objects.

Finally, if you're dealing with large amounts of data, consider converting it to JSON on the JavaScript side and passing it over to .NET in a single call. You'll get much better performance that way.

Good luck!

**Comment by hyzx86** [comment]
> ```C#
>foreach (var item in list) {
>    var names = ((DynamicObject)item).GetDynamicMemberNames();
>    dictList.Add(names.ToDictionary(name => name, name => ((dynamic)item)[name]));
>}
>```

Thanks for your demo

> In any case, it's likely that Jint and ClearScript expose script objects differently, so writing code specifically for one or the other is likely necessary. If so, then we aren't clear on why you're avoiding ClearScript's API.

In Jint, an array of objects is converted to `ExpandoObject[]` when passed to dotnet ,
So it can use methods overload  of C# object instances  , and in most cases, type conversions can be ignored

**Comment by ClearScriptLib** [comment]
>In Jint, an array of objects is converted to `ExpandoObject[]` when passed to dotnet ,

What if some of the array elements are primitive values?

**Comment by hyzx86** [comment]
> > In Jint, an array of objects is converted to `ExpandoObject[]` when passed to dotnet ,
> 
> What if some of the array elements are primitive values?

It will also be converted to the corresponding C# type

Just like this delegate

```C#
           new GlobalMethod
                {
                    Name = "loadContenItems",
                    Method = serviceProvider => (Func<string[], object>)((contentItemIds) =>
                    {
                        var contentManager = serviceProvider.GetRequiredService<IContentManager>();
                        return contentManager.GetAsync(contentItemIds).GetAwaiter().GetResult();
                    })
                },
```

There are some unit tests, I couldn't find the conversion test, but in my case it worked fine
https://github.com/sebastienros/jint/blob/main/Jint.Tests/Runtime/ArrayTests.cs

**Comment by ClearScriptLib** [comment]
>It will also be converted to the corresponding C# type

Our tests indicate that Jint converts arrays to `object[]`, and "normal" objects to `ExpandoObject`. That makes sense.
