### ISSUE TITLE
Using derived types with VBScript

### ISSUE THREAD

**Issue by EtienneLaneville** [microsoft/ClearScript#387]
Using the MSScriptControl, when dealing with a derived object that has been provided by the host using the base type, it is possible to access the derived object's properties and methods. For example:

```
public class Being
{
    public String Name { get; set; }

    public Being(string name)
    {
        this.Name = name;
    }

}
public class SpecialBeing : Being
{
    public String SpecialName { get; set; }
    public SpecialBeing(string name) : base(name)
    {
        this.SpecialName = "Special " + name;
    }
}
```

If the host returns an object that was created as a `SpecialBeing` but is returned as a `Being`, you would still be able to access the `SpecialName` property. Here's an example of a class that returns a `SpecialBeing` as a `Being`:

```
public class Creator
{
    public Being CreateBeing(string name)
    {
        if (name == "")
        {
            return null;
        }
        else
        {
            return new SpecialBeing(name);
        }

    }
}
```

In the ClearScript VBScriptEngine, accessing an object `CreateBeing` returns will throw an exception if its `SpecialName` property is accessed:

```
using (var host = new Microsoft.ClearScript.Windows.VBScriptEngine())
{

	host.HostWindow = new HostWindow();
	Creator creator = new Creator();

	host.AddHostObject("creator", creator);
	string code = "Dim objBeing\nSet objBeing = creator.CreateBeing(\"Felix\")\nMsgBox objBeing.SpecialName";
	host.Execute(code);

}
```

This will throw the following exception:
> An unhandled exception of type 'Microsoft.ClearScript.ScriptEngineException' occurred in ClearScript.Core.dll
> Object doesn't support this property or method: 'SpecialName'

Is there a way to cast the object to its derived type in the scripting engine or is it necessary to return the desired type from the host side? In this case, is it necessary to change the return type of `CreateBeing` in `Creator` to `SpecialBeing`?

I have tried the following:
```
using (var host = new Microsoft.ClearScript.Windows.VBScriptEngine())
{

	host.HostWindow = new HostWindow();
	Creator creator = new Creator();

	host.AddHostType(typeof(SpecialBeing));
	host.AddHostObject("creator", creator);
	host.AddHostObject("host", new ExtendedHostFunctions());

	host.Execute("Dim objBeing");
	host.Execute("Set objBeing = creator.CreateBeing(\"Felix\")");
	host.Execute("Dim objType");
	host.Execute("Set objType = host.typeOf(\"SpecialBeing\")");
	host.Execute("MsgBox host.cast(objBeing, objType).SpecialName");

}
```

This throws a 'Use of reflection is prohibited in this script engine' exception on the `Set objType = host.typeOf(\"SpecialBeing\")"` line.

Using `host.Execute("Set objType = host.type(\"SpecialBeing\")");` instead, I get the following exception:

> Could not find a specific type or generic type definition for 'SpecialBeing'

**Comment by ClearScriptLib** [comment]
Hi @EtienneLaneville,

>In the ClearScript VBScriptEngine, accessing an object `CreateBeing` returns will throw an exception if its `SpecialName` property is accessed:

That's correct. Values returned from the host are restricted to their declared types. As before with enums, this is by design and intended to ensure fidelity with .NET's type system, which is critical for correct method binding.

There are several ways to get the behavior you're looking for. The easiest is probably as follows:

``` C#
public class Creator
{
    [Microsoft.ClearScript.ScriptMember(ScriptMemberFlags.ExposeRuntimeType)]
    public Being CreateBeing(string name)
    {
```

No other changes should be necessary, but we'd like to address your subsequent findings for completeness.

>This throws a 'Use of reflection is prohibited in this script engine' exception on the `Set objType = host.typeOf(\"SpecialBeing\")"` line.

That's also correct. `HostFunctions.typeOf` and other reflection accessors are disallowed by default for code security reasons.

You could enable reflection via [`ScriptEngine.AllowReflection`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_AllowReflection.htm), but that's unnecessary in this case. To call `HostFunctions.cast`, you don't need a `System.Type` instance; you need the _host type_, which you've already exposed via `AddHostType`:

``` C#
host.Execute("Set objBeing = creator.CreateBeing(\"Felix\")");
host.Execute("MsgBox host.cast(SpecialBeing, objBeing).SpecialName");
```

BTW, `HostFunctions.typeOf` takes a host type, not a string. That is, if you enable reflection, `host.typeOf(SpecialBeing)` will yield the `System.Type` instance for `SpecialBeing`. It works exactly like `typeof(SpecialBeing)` in C#.

>Using `host.Execute("Set objType = host.type(\"SpecialBeing\")");` instead, I get the following exception:

Right. `ExtendedHostFunctions.type` requires a fully qualified type name. You don't need it in this case, and we recommend that you avoid it – and the `ExtendedHostFunctions` type in general – for code security reasons.

Good luck!

**Comment by EtienneLaneville** [comment]
Fantastic, `host.cast(SpecialBeing, objBeing)` works. I think I have all I need now. Thanks for all the help getting me going.
