### ISSUE TITLE
Version strings not updated with 5.5.1.1

### ISSUE THREAD

**Issue by 4C51** [Microsoft/ClearScript#41]
Release was tagged, but no version strings were updated, intended?

**Comment by ClearScriptLib** [comment]
Hi @4C51,

Version 5.5.1.1 is a hotfix for a [serious bug](https://github.com/Microsoft/ClearScript/issues/34). Because such releases undergo expedited testing, our policy is for them to include minimal code changes.

However, we're fairly confident that bumping the version number incurs low risk, so we'll post an update and creep the tag.

Thanks!
