### ISSUE TITLE
System.ArgumentException: Delegate to an instance method cannot have null 'this'.

### ISSUE THREAD

**Issue by viceice** [microsoft/ClearScript#416]
We strangely get a´n `ArgumentException` when disposing a `V8ScriptEngine`

```
System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at Microsoft.ClearScript.V8.V8DebugAgent.Dispose()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.DestroyDebugAgent(IntPtr pAgent)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Impl_Windows_X64.V8Entity_Release(Handle hEntity)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Impl_Windows_X64.Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative.V8Entity_Release(Handle hEntity)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.InvokeNoThrow(Action`1 action)
   at Microsoft.ClearScript.V8.SplitProxy.V8EntityHolder.ReleaseEntity()
   at Microsoft.ClearScript.V8.SplitProxy.V8IsolateProxyImpl.Dispose()
   at Microsoft.ClearScript.V8.V8ScriptEngine.Dispose(Boolean disposing)
   at Microsoft.ClearScript.ScriptEngine.Dispose()
```

We can't reproduce it in local tests. It only happens on IIS when we start a separate AppDomain.
We then pass a HTTP request to the app domain, where the engine is created / used and disposed.

Any ideas to ivestigate further?

We can reproduce with `7.3.2`

**Comment by viceice** [comment]
Version 7.3.1 works fine.

**Comment by ClearScriptLib** [comment]
Hi @viceice,

Thanks for reporting this issue! It's a bug 😅

We've found a way to reproduce the exception, but we can't be sure that the underlying bug is the same as in your case, because ours is _not_ a regression in 7.3.2.

Here's what we found. When you instantiate `V8ScriptEngine` with `V8ScriptEngineFlags.EnableDebugging`, the engine internally instantiates [`TcpListener`](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener) with the specified debug port, or 9222 by default. If the `TcpListener` constructor fails, the engine continues normally with debugging disabled but then throws that exception when you dispose it.

According to the .NET documentation, and given ClearScript's code, the [relevant constructor](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener.-ctor?view=net-6.0#system-net-sockets-tcplistener-ctor(system-net-ipaddress-system-int32)) can only fail if the specified debug port is invalid – that is, either negative or greater than 65535. Indeed, we can easily reproduce the exception as follows:

``` C#
var engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging, 70000);
engine.Dispose();
```

Given all that, there are three ways your application could be throwing that exception:
1. You're specifying a bad V8 debug port.
2. In your scenario, the `TcpListener` constructor is failing for an undocumented reason.
3. You're encountering a different bug.

ClearScript's next release, hopefully coming sometime next week, will address (1) and (2). Hopefully that'll resolve your issue. In the meantime, if you could somehow _rule out_ (1) and (2), that might be helpful. And you should be able to work around the issue temporarily by _not_ specifying `V8ScriptEngineFlags.EnableDebugging`.

Thank you!

**Comment by viceice** [comment]
We don't use the debugging feature, we create it like this:
```cs
 var flags = V8ScriptEngineFlags.EnableDynamicModuleImports
     | V8ScriptEngineFlags.EnableTaskPromiseConversion
     | V8ScriptEngineFlags.EnableDateTimeConversion
     | V8ScriptEngineFlags.EnableValueTaskPromiseConversion
     | V8ScriptEngineFlags.EnableStringifyEnhancements;
 var engine = new V8ScriptEngine(flags)
 {
     AllowReflection = false,
 };
```

**Comment by ClearScriptLib** [comment]
Hi @viceice,

>We don't use the debugging feature, we create it like this:

Thanks for the info!

We just found something very interesting: The bug can be triggered by accidentally combining the 7.3.2 managed assemblies with the older 7.3.1 _native_ assembly (ClearScriptV8.win-x64.dll). Could this be happening in your IIS deployment, by any chance?

Cheers!

**Comment by viceice** [comment]
maybe, will check this. but I'm out of office for two weeks, will send this to my co-worker.

**Comment by ClearScriptLib** [comment]
>maybe, will check this. but I'm out of office for two weeks, will send this to my co-worker.

Sounds great. Thanks!

The assembly mismatch is almost certainly the issue here. We can reproduce it with this trivial app:

``` C#
using Microsoft.ClearScript.V8;
using var engine = new V8ScriptEngine(
    V8ScriptEngineFlags.EnableDynamicModuleImports |
    V8ScriptEngineFlags.EnableTaskPromiseConversion |
    V8ScriptEngineFlags.EnableDateTimeConversion |
    V8ScriptEngineFlags.EnableValueTaskPromiseConversion |
    V8ScriptEngineFlags.EnableStringifyEnhancements);
```

That's for a project defined as follows (note the package version mismatch):

``` XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ClearScript.Core" Version="7.3.2" />
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.3.2" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.3.1" />
  </ItemGroup>
</Project>
```

Interestingly, the behavior depends on the flags passed to the `V8ScriptEngine` constructor, and your specific combination of flags always triggers the bug. Of course, even without a bug, mixing different versions of ClearScript assemblies is unsupported and can result in unpredictable behavior.

Good luck!

**Comment by viceice** [comment]
agreed, those versions get accidentally mixed on deployment. we're investigating the cause and fix it.

on normal local or CI builds all if working fine. so it must be some production deployment error.

**Comment by viceice** [comment]
Could it be a problem that we've multiple appdomains, which can have different clearscript versions?

So the appdomain with 7.3.1 is starting first, and later a domain with 7.3.2 is started and is reusing the native from 7.3.1 instead of loading the newer version?

**Comment by ClearScriptLib** [comment]
>Could it be a problem that we've multiple appdomains, which can have different clearscript versions?

Yes. Application domains are a purely managed concept, so native code is oblivious to it. That is, application domains share native assemblies.

ClearScript supports multiple application domains, but if they use V8, they must all use the same ClearScript version.

Sorry!

**Comment by viceice** [comment]
thanks for confirming, we'll try to refactor our code to use separate process instead of app domains. 

that should fix the problem and probably some more 😅

**Comment by viceice** [comment]
closed, because it's not a clearscript bug.

**Comment by ClearScriptLib** [comment]
[Version 7.3.3](https://github.com/microsoft/ClearScript/releases/tag/7.3.3) fixed the debug port issue and added a check to prevent version mismatches between managed and native V8 assemblies.

**Comment by KurtGokhan** [comment]
I am getting [this error](https://github.com/ReactUnity/core/actions/runs/3151172256/jobs/5127284207#step:12:15900) when using 7.3.3:
"System.InvalidOperationException : V8 native assembly: loaded version [unknown] does not match required version 7.3.3"

This only happens when native library is first loaded (i.e. first test which uses ClearScript). Then it works correctly. I have only observed this in Ubuntu Github Actions so far. I don't know if it happens in other platforms.

@ClearScriptLib  any idea why that would happen?

**Comment by ClearScriptLib** [comment]
>@ClearScriptLib any idea why that would happen?

Yes. Please see Issue #418.
