### ISSUE TITLE
BUG:  Host functions not called when javascript has overloaded functions

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [microsoft/ClearScript#420]
# Description
Overloaded host object functions not called when javascript code has an overloaded function.

See also #421 

# Steps to reproduce
* run project
* observe console output

# Expected
* some console output
```bash
TestStreamer | WriteStream | {"Line":64,"Character":128,"Message":"Needs more work"}
TestStreamer | schema | {"Line":64,"Character":128,"Message":"Needs more work"}
```

# Observed
* no output

# Configuration
* Microsoft.ClearScript Version="7.3.4"
* Microsoft.ClearScript.V8.Native.linux-x64 Version="7.3.4"
* Windows 10
* .NET Core 6.0.302

[v8Test-bug-host-not-called.zip](https://github.com/microsoft/ClearScript/files/9733343/v8Test-bug-host-not-called.zip)

**Comment by ClearScriptLib** [comment]
Hi @TrevorDArcyEvans,

JavaScript doesn't support method overloading. In your code here:

``` JavaScript
class TestStreamer
{
  write(obj)
  {
    host.WriteStream("TestStreamer", JSON.stringify(obj));
    host.WriteStream("TestStreamer", "schema", JSON.stringify(obj));
  }

  write(schema, obj)
  {
    //host.WriteStream(this.name, schema, JSON.stringify(obj));
  }
}
```

The second `write` method overwrites the first. Since it contains only a comment, it produces no output.

In JavaScript, a method is just a property whose value is a function. You can't have two properties with the same name, so method overloading is impossible.

Good luck!
