### ISSUE TITLE
Add functions into namespace

### ISSUE THREAD

**Issue by CrosRoad95** [microsoft/ClearScript#436]
question: how can i add host object, type into a namespace?
i'm asking because i have functions from multiple categories and i want to keep them in separete files while still accessing them from under some namespace

example:
```csharp
class Foo{
  void FooFunc(...){...}
}
class Bar{
  void BarFunc(...){...}
}
```
and in js:
```
namespace.fooFunc(...)
namespace.barFunc(...)
```

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

Please help us understand your scenario.

>`namespace.fooFunc(...)`
`namespace.barFunc(...)`

Since `FooFunc` and `BarFunc` are instance methods, you must specify an instance of the appropriate class in order to invoke them. Your desired JavaScript syntax doesn't appear to accommodate that requirement.

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you can provide more information about this topic. Thank you!
