### ISSUE TITLE
Q: Python & Lua & C# support

### ISSUE THREAD

**Issue by ParadiseFallen** [microsoft/ClearScript#476]
is there a way to support other languages?

**Comment by ClearScriptLib** [comment]
Hi @ParadiseFallen,

>is there a way to support other languages?

While new [`ScriptEngine`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptEngine.htm) subclasses are certainly possible, they'd have to be implemented within the ClearScript project. That's because some `ScriptEngine` abstract members are [internal](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/internal).

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions about this topic. Thank you!
