### ISSUE TITLE
WebApplication in c# with V8ScriptEngine crashes on Mac x64

### ISSUE THREAD

**Issue by Morpheus121** [microsoft/ClearScript#483]
Hello,
I have a problem with V8 Script engine. Application crashes when I use WebApplication project type in C#. 
I work on a Mac with Intel processor. 
OS 12.6 Monterey. 
IDE Rider  2022.3.1. 
.NET 7.0.2 

Used nuget packages:
Microsoft.ClearScript.V8 7.3.7
Microsoft.ClearScript.Core 7.3.7
Microsoft.ClearScript.V8.ICUData 7.3.7
Microsoft.ClearScript.V8.Native.osx-x64 7.3.7

When I create WebApplication from template in Rider and paste this example from your examples
`using var engine = new V8ScriptEngine();
// expose a host type
engine.AddHostType("Console", typeof(Console));
engine.Execute("Console.WriteLine('{0} is an interesting number.', Math.PI)");`

The application crashes when a new object V8ScriptEngine is created with this error message in console:
Fatal error in , line 0
Check failed: 12 == (*__error()).
FailureMessage Object: 0x7ff7bb170820

When I create ConsoleApplication project type and paste example code, everything works.

**Comment by Morpheus121** [comment]
I am attaching an example project with a non-working Web Application and a working Console Application
[V8Tests.zip](https://github.com/microsoft/ClearScript/files/10557657/V8Tests.zip)

**Comment by ClearScriptLib** [comment]
Hello @Morpheus121,

We can't reproduce your issue on macOS 13.0 x64:

![image](https://user-images.githubusercontent.com/12966733/216083520-aec946a0-a701-46ba-add1-083e70751948.png)

Does your issue produce a crash report in the Console app?

Thanks!

**Comment by Morpheus121** [comment]
It does not produce a crash report.
All I have is
![image](https://user-images.githubusercontent.com/31939364/216093092-b24e596d-80ab-49b6-862a-02b0ab49a7cd.png)

I tried to run it _dotnet run_ on the project WebApplication and I have the same output as you. The problem occurs only when I debug WebApplication. I tried Debug in Visual Studio and Rider with the same error

**Comment by ClearScriptLib** [comment]
>The problem occurs only when I debug WebApplication.

Please share the exact steps that reproduce the crash. Thanks!

**Comment by Morpheus121** [comment]
Steps to reproduce:
Open attached project in Visual Studio or Rider.
Choose WebApplication as target for Debug.
Place breakpoint on line _using var engine = new V8ScriptEngine();_
Run Debug
=> Debugger stops on this line
press go to next line button
=>Crash with error

**Comment by ClearScriptLib** [comment]
>Open attached project in Visual Studio or Rider.

Just to be clear, are you talking about [Visual Studio Code](https://code.visualstudio.com/) or [Visual Studio for Mac](https://visualstudio.microsoft.com/vs/mac/)?

**Comment by Morpheus121** [comment]
Yes, it is Visual Studio for Mac

**Comment by ClearScriptLib** [comment]
Hi @Morpheus121,

We've reproduced this with Visual Studio for Mac. Oddly, it only happens on macOS x64; Apple Silicon is unaffected.

It looks like V8 is crashing the process [here](https://github.com/v8/v8/blob/e33c3a09b31af5b69286f904a378fcbfb36a726d/src/base/platform/platform-posix.cc#L485). We're investigating.

Thanks!

**Comment by ClearScriptLib** [comment]
Hi @Morpheus121,

It turns out that we've seen this issue before, but only on Apple Silicon. Maybe something has changed in macOS, .NET, or Visual Studio since then, but now we can only reproduce it on x64.

Anyway, what's happening is that V8's call to [`mprotect`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/mprotect.html) is returning EACCES in the debugging environment. It has something to do with macOS's strict enforcement of just-in-time (JIT) compilation policies.

Our understanding is that JIT compilation is blocked by default but can be enabled via [entitlements](https://developer.apple.com/documentation/bundleresources/entitlements). Such policies are enforced at the application level, so ClearScript and other libraries can't work around them. However, we've found that libraries carrying a developer signature can bypass _some_ enforcement. That appears intended to streamline developer workflows.

Given all that, we're aware of two ways to work around this issue.

First, if your application can detect that it's being debugged – via command-line flag, configuration setting, or some other means – it can use [`V8Settings.GlobalFlags`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8Settings_GlobalFlags.htm) to disable JIT compilation. Or, if JavaScript performance isn't critical during development, you can control JIT compilation based on your Debug/Release configuration.

Second, you can use the following procedure to apply a developer signature to your copy of ClearScript's V8 dynamic library:

1. Locate your cached copy of `ClearScriptV8.osx-x64.dylib`. Run `dotnet nuget locals global-packages --list` to display your NuGet cache path. It should be something like `~/.nuget/packages/`. On the command line, `cd` to that path, and then to `./microsoft.clearscript.v8.native.osx-x64/7.3.7/runtimes/osx-x64/native`. The file should be there.

1. Patch the file as follows:
`codesign --sign - --options linker-signed --force ClearScriptV8.osx-x64.dylib`

1. Clean, rebuild, and run your test project.

Please let us know if either workaround works for you.

Good luck!

**Comment by Morpheus121** [comment]
Thanks for the workaround!
It works for me.

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts or findings related to this topic. Thank you!
