### ISSUE TITLE
Request to support Deno

### ISSUE THREAD

**Issue by zakuru** [microsoft/ClearScript#487]
Hello,

Would is be possible to support DENO as JS environment ?
That would made server side rendering on .net core app using REACT / VUE code seamless -

**Comment by zakuru** [comment]
sorry  i think the good repo to post this request is https://github.com/Taritsyn/JavaScriptEngineSwitcher/ right ?
Posted there 
Thanks 
https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/107

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional comments on this topic. Thank you!

**Comment by anonhostpi** [comment]
On a serious note though, I think this is something that would suit this project well.

One of the problems with embedding node is Node's complexity. Deno's source code is simpler than node and is less prone to memory leaks both due to them being written in Rust. Deno is also designed to be embeddable:
- https://docs.deno.com/runtime/manual/advanced/embedding_deno/

The only issue is that it is written to be embedded in another Rust application, so FFIs would have to be written for in addition to C# bindings, though I don't imagine that to be much more of a complex process than writing the C# bindings themselves.

**Comment by anonhostpi** [comment]
Reposted instead of reopening since I don't own this issue.
