### ISSUE TITLE
HostDelegate function with array parameter and call it with `apply`

### ISSUE THREAD

**Issue by JangoBoogaloo** [microsoft/ClearScript#497]
I am trying to delegate [Path.Combine](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=net-7.0) method into javascript and I am not able to call the method with `apply`. Can I get some hint for how to delegate array parameter method?
```C#
engine.AddHostObject("__path__combine", HostItemFlags.GlobalMembers, new Func<string[], string>(Path.Combine));
engine.Execute("var x = ['a', 'b', 'c']; __path__combine.apply(x)");
```

**Comment by ClearScriptLib** [comment]
Hi @JangoBoogaloo,

Instead of using `Func`, you can define a delegate type that captures `Path.Combine`'s support for [parameter arrays](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/params):

``` C#
private delegate string PathCombine(params string[] args);
```

Now you can achieve the desired result via JavaScript's [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax):

``` C#
engine.AddHostObject("__path__combine", new PathCombine(Path.Combine));
engine.Execute("var x = ['a', 'b', 'c']; __path__combine(...x)");
```

Good luck!

**Comment by JangoBoogaloo** [comment]
It works as expected. Thanks!
