### ISSUE TITLE
Methods from Derived Classes Not Bound in ClearScript

### ISSUE THREAD

**Issue by herki18** [microsoft/ClearScript#607]
I may have misunderstood how binding works in ClearScript, but I'm encountering an issue where methods from derived classes are not accessible. We have a method createElement that returns an object of type IElement. However, the actual object being returned is an instance of a derived class, HtmlDivElement, which inherits from IElement. The problem is that ClearScript only binds methods and properties from IElement and its ancestors. This results in methods specific to HtmlDivElement being inaccessible from JavaScript.

**Example:**

```csharp
public interface IElement
{
    void SetAttribute(string name, string value);
    string GetAttribute(string name);
}

public class HtmlDivElement : IElement
{
    public void SetAttribute(string name, string value) 
    {
        // Set attribute logic
    }

    public string GetAttribute(string name) 
    {
        // Get attribute logic
        return string.Empty;
    }

    public void SetDivSpecificMethod() 
    {
        // Method specific to HtmlDivElement
    }
}

```

**JavaScript Example:**

```javascript
var div = document.createElement("div");
div.setAttribute("id", "myDiv");

// This fails because methods specific to HtmlDivElement are not bound
div.setDivSpecificMethod(); // Error: setDivSpecificMethod is not a function
```

**Question:**  
How can I ensure that ClearScript binds methods from the derived class (`HtmlDivElement`) so that they are accessible in JavaScript? Is there a way to expose these methods while keeping the inheritance structure intact?

**Comment by ClearScriptLib** [comment]
Hi @herki18,

The behavior you're seeing is by design. It's an effect of a ClearScript feature called _type restriction_, which enhances the ability of script languages to consume strongly typed .NET APIs.

>`// This fails because methods specific to HtmlDivElement are not bound`
`div.setDivSpecificMethod(); // Error: setDivSpecificMethod is not a function`

That's right. The variable `div` is effectively of type `IElement`. If this were C# code, you couldn't call `SetDivSpecificMethod` without casting, and the same applies to JavaScript.

Type restriction is important for .NET member binding. Suppose you wanted to pass `div` to a .NET method overloaded as follows:

```csharp
void DoSomething(IElement element);
void DoSomething(HtmlDivElement element);
```

Without type restriction, the first overload would be inaccessible, and that's just the tip of the iceberg. .NET APIs often rely heavily on precise type tracking for correct member binding, ambiguity resolution, type inferencing, generic type and method instantiation, etc.

That said, ClearScript does give applications the following controls over type restriction:

- Members whose return type is [`object`](https://learn.microsoft.com/en-us/dotnet/api/system.object) are exempt from type restriction.
- [`HostFunctions.cast`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_cast__1.htm) is a script-callable type casting function.
- [`ScriptMemberAttribute.Flags`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptMemberAttribute_Flags.htm) can disable type restriction for an individual member via [`ScriptMemberFlags.ExposeRuntimeType`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptMemberFlags.htm).
- [`ScriptEngine.DisableTypeRestriction`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_DisableTypeRestriction.htm) provides control at the script engine level.

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions about this topic. Thank you!
