### ISSUE TITLE
Update V8 to a more recent version

### ISSUE THREAD

**Issue by JohnLudlow** [Microsoft/ClearScript#73]
We'd like to use a recent version of V8 with ClearScript. 6.8 is now considered "discontinued" in terms of Chrome versions (https://en.wikipedia.org/wiki/Google_Chrome_version_history) and 6.9 is current stable. 

Is 6.9 / 7.0 considered good for use with ClearScript? Could V8Update.cmd be updated to recommend a 6.9 or 7.0 version?

**Comment by ClearScriptLib** [comment]
Hi @JohnLudlow,

Unfortunately, as it is a side project, ClearScript can't keep up with V8's aggressive release pipeline, which issues a new stable version every 6-8 weeks and immediately downgrades the previous one to "discontinued".

As our policy is to couple ClearScript only with stable V8 versions, and since we can't synchronize our releases with theirs, we can hope for ClearScript to be coupled with a supported V8 version for 6-8 weeks at absolute best.

ClearScript 5.5.4 will be coupled with V8 7.0, and we're hoping to release it in a few weeks. Unfortunately V8 6.9 introduced a breaking change and can't be used with the current ClearScript sources without modification.

Thanks!

**Comment by ClearScriptLib** [comment]
>Is there a list of changes planned for 5.5.4 (other than supporting V8 7.0)?

Just the issues you see here on GitHub, minus major projects such as support for new script engines and alternate .NET runtimes.

**Comment by JohnLudlow** [comment]
OK thanks. And some of those tasks will depend on what other projects do, I expect (supporting .NET Core springs to mind, since you need them to add reflection if I'm not mistaken?)

We'll keep an eye on the issues list and use that to plan how we use ClearScript

**Comment by ClearScriptLib** [comment]
[Version 5.5.4](https://github.com/Microsoft/ClearScript/releases/tag/5.5.4) is paired with V8 7.0.
