### ISSUE TITLE
How to use native JS object as argument in host function?

### ISSUE THREAD

**Issue by dwanboweb** [Microsoft/ClearScript#78]
I wants to write code like this in script:
`clr.System.String.Join(',',[1,2,3,4])`
OR
`//void mHostMethod(Dictionary<string, object> arg)

mHostMethod({
a:1,
b:2
})
`

What's the right way for my attention?
Thank you very much

**Comment by ClearScriptLib** [comment]
Hi @dwanboweb,

ClearScript doesn't convert collections automatically, but you can easily do it yourself. Here are some examples.

For `mHostMethod`, you could create an overload that takes a script object and converts it into a dictionary:

``` C#
public class Foo {
    public void mHostMethod(Dictionary<string, object> arg) {
        foreach (var pair in arg) {
            Console.WriteLine(pair);
        }
    }
    public void mHostMethod(ScriptObject arg) {
        var dict = new Dictionary<string, object>();
        foreach (var name in arg.GetDynamicMemberNames()) {
            dict[name] = ((dynamic)arg)[name];
        }
        mHostMethod(dict);
    }
}
```

And then:

``` C#
engine.Script.foo = new Foo();
engine.Execute("foo.mHostMethod({ a:1, b:2 })");
```

As for `string.Join`, unfortunately you can't overload an external method, but you can provide a separate class:

``` C#
public static class StringUtil {
    public static string Join(string separator, ScriptObject arg) {
        var list = new List<object>(((dynamic)arg).length);
        for (var i = 0; i < list.Capacity; ++i) {
            list.Add(((dynamic)arg)[i]);
        }
        return string.Join(separator, list);
    }
}
```

And then:

``` C#
engine.AddHostType(typeof(StringUtil));
Console.WriteLine(engine.Evaluate("StringUtil.Join(',', [1, 2, 3, 4])"));
```

You could also perform the conversion in script code if that's more convenient. There are many ways to do it, and we can't say which is best for you. That's why ClearScript favors easy access over automatic conversion.

Good luck!

**Comment by dwanboweb** [comment]
thank you.This is Just what I want.
