### ISSUE TITLE
Dynamic variable serialization

### ISSUE THREAD

**Issue by BlackGad** [Microsoft/ClearScript#91]
Is it possible to extract dynamic value (V8ScriptItem), serialize it and later insert as host item into another V8Engine instance (right way)?

I can explore all properties via Engine.Script property, can enumerate whole structure of dynamic object. Even determine array types via 
```
engine.Script.Array.isArray(value);
```
(Hope there is better way to do this)

But I cannot create object instance of the same V8ScriptItem type in another engine programmatically from host side. (with out reflection)

**Comment by BlackGad** [comment]
My data is not simple :) I figured out how to process my case but found 5 different issues. 

Here is example: https://github.com/BlackGad/ClearScriptIssue

Issue 1: Invalid dynamic object constructor parsing on Evaluate
```
engine.Evaluate("{a: 'b'}")
```
Issue 2: Invalid not typed array constructor parsing on Evaluate
```
engine.Evaluate("['a','b']")
```
Issue 3: Strange behavior when 'let' was used between 2 Evaluate calls.
```

**Comment by BlackGad** [comment]
Could you please comment post above? Maybe I just do something in wrong way.

**Comment by ClearScriptLib** [comment]
Hi @BlackGad,

**Issue 1**

The JavaScript syntax `{ a: 'b' }` is ambiguous. You're expecting it to be interpreted as an object literal, but the parser sees it as a [block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block) containing a [labeled](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label) expression. Try enclosing it in parentheses.

**Issue 2**

We're not seeing any incorrect behavior. In your test program, both

``` C#
var simpleNotTypedArray = engine.Evaluate("['a','b']");
```

and

``` C#
var simpleNotTypedArray = engine.Evaluate("let test2 = ['a','b']; test2;");
```

produce the same result – a JavaScript array with two elements.

**Issue 3**

Using `let` with the same variable name more than once in the same scope is a [syntax error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Redeclarations).

**Issue 4**

`AddHostObject` doesn't work with fundamental values such as numbers as strings. See Issue #90 for an explanation.

Normally it doesn't work with script objects for the same reason; a script object, when handed back to its engine of origin, is stripped of its .NET proxy and therefore can't support some features of `AddHostObject`.

Instead of using `AddHostObject` you can simply do this:

``` C#
engine.Script.test = deserialized;
```

or this:

``` C#
engine.Script["test"] = deserialized;
```

As you've noticed, `AddHostObject` can successfully expose a _foreign_ script object, and that's because in that case the managed proxy is retained and all access to the object continues to go through ClearScript.

Note that exposing script objects across engine instances – via `AddHostObject` or the dynamic `Script` property – is supported but not recommended. Accessing a foreign script object is extremely expensive and can lead to deadlocks unless very carefully managed.

**Issue 5**

As is the case with host objects, the engine doesn't have direct access to a foreign script object. Instead, it has a proxy that routes access through ClearScript. That proxy is an instance of a special ClearScript-defined JavaScript prototype, and the actual type information of its external target is inaccessible to the local implementation of `Array.isArray`.

Let us know if you have any additional questions.

Good luck!

**Comment by BlackGad** [comment]
**Issue 1** 
You are right, missed code blocks %) replaced with
```
dynamic result = engine.Evaluate($"new Object()");
```
**Issue 2** 
Same, I made a mistake somewhere, sorry :)

**Issue 3** 
Please clarify my understanding
ClearScript scope structure looks like this:
```
outer scope <- engine.Script bridge here
{
processing scope <- Evaluate executing here asynchronously
}
```
That's why **let** variable already defined on second call via Evaluate and not accessible via **engine.Script** bridge

**Issue 4 and Issue 5** Thank you for detailed explanation!

**Comment by ClearScriptLib** [comment]
HI @BlackGad,

Regarding Issue 3:

1. [`Script`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_Script.htm) is a managed reference to the [global object](https://developer.mozilla.org/en-US/docs/Glossary/Global_object).

1. [`Evaluate`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_ScriptEngine_Evaluate.htm) and[ `Execute`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_ScriptEngine_Execute.htm) run code within the [global scope](https://developer.mozilla.org/en-US/docs/Glossary/global_scope), where [`this`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Global_Context) refers to the global object.

1. In the global scope, `let` declares a global variable, but it does _not_ add a property to the global object (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Scoping_rules_2)). That's why you get the syntax even though the variable isn't accessible via `Script`.

Cheers!

**Comment by BlackGad** [comment]
Thank you!

**Comment by ClearScriptLib** [comment]
Hello @hyzx86,

Yes, the test and your sample code still work. You can see it in action [here](https://dotnetfiddle.net/sNNy4C).

Any idea what you might be doing differently?

**Comment by hyzx86** [comment]
Hi @ClearScriptLib ,
Thanks for your confirm

Notice that your sample is used in the `Microsoft. ClearScript.Linux-x64`

But I'm referring to these two packages
```
		<PackageManagement Include="Microsoft.ClearScript.V8.Native.linux-x64" Version="$(ClearScriptVersion)" />
		<PackageManagement Include="Microsoft.ClearScript.V8.Native.win-x64" Version="$(ClearScriptVersion)" />
```

I am using ClearScript in Asp.net core project
If I want to be compatible with windows and linux servers.
Which packages should I refer to?

thanks

**Comment by hyzx86** [comment]
Updated to this, trying

``` 
<PackageReference Include="Microsoft.ClearScript.V8"/>
<PackageReference Include="Microsoft.ClearScript.Core"  />
<PackageReference Include="Microsoft.ClearScript.V8.ICUData" />
```

**Comment by hyzx86** [comment]
Now the error message is :
`Cannot load ClearScript V8 library. Load failure information for ClearScriptV8.win-x64.dll`


![image](https://user-images.githubusercontent.com/15613121/214357216-12f36a4f-2bc1-4084-bf59-b51ea3fef0ab.png)

**Comment by ClearScriptLib** [comment]
Hi @hyzx86,

Try using the composite packages for Windows and Linux x64:

1. [Microsoft.ClearScript](https://www.nuget.org/packages/Microsoft.ClearScript)
2. [Microsoft.ClearScript.linux-x64](https://www.nuget.org/packages/Microsoft.ClearScript.linux-x64)

If you're still unable to make it work, consider sharing a minimal project that reproduces the problem. We'll be happy to take a look.

Good luck!

**Comment by ClearScriptLib** [comment]
>Also, what's the difference between the Native.xxx versions?

The V8 JavaScript engine is native code (written in C++), so there's a different binary version for each supported hardware platform and operating system.

The easiest way to incorporate ClearScript is to reference one or more of the [composite packages](https://github.com/microsoft/ClearScript#composite-packages), each of which includes everything you need for a single hardware/OS combination.

The [component](https://github.com/microsoft/ClearScript#component-packages) and [native](https://github.com/microsoft/ClearScript#v8-native-assembly-packages) packages can be referenced individually to minimize package download, but it's easier and less error-prone to use the composite packages.

**Comment by hyzx86** [comment]
Thanks!
