### ISSUE TITLE
Derive from CLR class in TypeScript/JavaScript

### ISSUE THREAD

**Issue by ezolotko** [Microsoft/ClearScript#93]
What is the recommended way to achieve the following: "derive" from a CLR type (ideally in TypeScript, but using JS is also fine) and override some members in it? For example, this would be an ideal way to achieve this in TypeScript:

class MyForm  extends System.Windows.Forms.Form
{
}

Where System.Windows.Forms.Form is a ClearScript host type - but this doesn't work.
Thank you.

**Comment by ClearScriptLib** [comment]
Hi @ezolotko,

There's no single recommended way to derive JavaScript "classes" from .NET types. The two object systems are radically different. Interception allows ClearScript to create JavaScript proxies to .NET resources, but these proxies don't follow JavaScript's prototypal inheritance conventions.

That said, there are many ways to integrate host types into JavaScript's "class" system. One possibility is to link a host object into the prototype chain. Consider a function like this:

``` JavaScript
function HostClass(hostType) {
    return class {
        constructor() {
            let target = new hostType(...arguments);
            Object.defineProperty(this, 'super', { value: target });
            Object.setPrototypeOf(this, new Proxy(Object.getPrototypeOf(this), {
                has: (proto, key) => key in proto || key in target,
                get: (proto, key) => key in proto ? proto[key] : target[key]
            }));
        }
    };
}
```

With this function in place, you could do this:

``` C#
engine.AddHostType(typeof(Console));
engine.AddHostType(typeof(Random));
engine.Execute(@"
    class MyRandom extends HostClass(Random) {
        constructor() {
            super(...arguments);
        }
        Next() {
            Console.WriteLine('In Next override');
            return this.super.Next(...arguments);
        }
    }
    let random = new MyRandom();
    for (let i = 0; i < 10; ++i) {
        Console.WriteLine(random.Next(100));
    }
");
```

The downside of this approach is that you must use `this.super` to set host object properties since JavaScript property assignment doesn't go through the prototype chain.

Another possibility is to define pass-through properties on the derived object:

``` JavaScript
function HostClass2(hostType) {
    return class {
        constructor() {
            let target = new hostType(...arguments);
            for (let name in target) {
                Object.defineProperty(this, name, {
                    configurable: true,
                    get: () => target[name],
                    set: value => target[name] = value
                });
            }
        }
    };
}
```

And then:

``` JavaScript
class MyRandom2 extends HostClass2(Random) {
    constructor() {
        super(...arguments);
        let superNext = this.Next;
        Object.defineProperty(this, 'Next', {
            value: function() {
                Console.WriteLine('In Next override');
                return superNext(...arguments);
            }
        });
    }
}
let random2 = new MyRandom2();
for (let i = 0; i < 10; ++i) {
    Console.WriteLine(random2.Next(100));
}
```

This scheme gives you easier access to CLR property setters, but it makes overriding more cumbersome.

These are just a couple of ideas, and since each has advantages and disadvantages, you'll have to choose an approach that works for you.

Good luck!

**Comment by ezolotko** [comment]
Thank you very much for your reply! We will give the options you suggested a try and see what works for us.
