### ISSUE TITLE
System.OperationCanceledException in AddHostObject

### ISSUE THREAD

**Issue by ezolotko** [Microsoft/ClearScript#95]
We have two questions related to adding host objects:
1. We are encountering the following exception: System.OperationCanceledException: 'Namespace conflicts with 'HostType' at 'System.Internal.HandleCollector'' while executing the following code:
`engine.AddHostObject("clr", HostItemFlags.GlobalMembers, new HostTypeCollection("mscorlib", "System.Windows.Forms"));
`
The same exception occurs with "System.Drawing" instead of "System.Windows.Forms". However, with "System.Core" it works fine.

2. With the following code:
```
engine.AddHostObject("clr1", HostItemFlags.GlobalMembers, new HostTypeCollection("mscorlib"));
engine.AddHostObject("clr2", HostItemFlags.GlobalMembers, new HostTypeCollection("System.Drawing"));
engine.Execute("System.Console.WriteLine(\"Hi\")");
```
The engine.Execute line throws an exception Microsoft.ClearScript.ScriptEngineException: 'TypeError: Cannot read property 'WriteLine' of undefined', which probably indicates that the mscorlib host objects got replaced by the System.Drawing host objects. Is there a way to change this behavior and merge the two or more assemblies together in the global scope?

**Comment by ClearScriptLib** [comment]
Hi @ezolotko,

Each object exposed with `GlobalMembers` is pushed onto a stack. In your second example, since both objects have top-level `System` nodes, script code can only access the one from **System.Drawing**, which has no `Console` property.

Reversing the `AddHostObject` call order wouldn't help; you'd just run into the same issue with other classes in common namespaces.

The right way is to merge the classes from both assemblies into a single type collection, as you do in your first example. The problem there is that **mscorlib** has a class named "System.Internal" that conflicts with a namespace in **System.Windows.Forms**.

To resolve this conflict you can provide a type filter when constructing your type collection:

``` C#
Predicate<Type> filter = type => type.FullName != "System.Internal";
engine.AddHostObject("clr", HostItemFlags.GlobalMembers, new HostTypeCollection(filter, "mscorlib", "System.Windows.Forms"));
```

Even better, if it's sufficient in your case, is to include only public types:

``` C#
Predicate<Type> filter = type => type.IsPublic;
```

That really should be the default filter, but it's a breaking change, so we haven't changed it.

Good luck!

**Comment by ezolotko** [comment]
Thank you very much for the clarifications, and for the working solution.
