### ISSUE TITLE
Question about performance characteristics

### ISSUE THREAD

**Issue by erik-kallen** [Microsoft/ClearScript#98]
I have the attached program. What it does is that it spawns a bunch of threads and computes some Javascript in a loop on each of the threads. I would expect this to use 100% of one CPU per thread, however, that is not at all what I see. I have a machine with 4 cores and hyperthreading, thus 8 logical processors.

When I run the program with one thread, all my CPUs start working a little as shown below. Total utilization is around 25%. With one thread, 1000 runs take about 15 seconds on my machine.

![image](https://user-images.githubusercontent.com/688028/51522795-76acb300-1e2a-11e9-9291-c94e068687a1.png)

When I up the number of threads to 2, the same thing happens: All CPUs start working, a little harder this time so total CPU utilization becomes around 50%. 1000 runs still take approximately 15 seconds.

However, when I up the number of threads to 4, things get more interesting. This puts the utilization around 80%, split across all CPUs, as shown in the image below. Now, with 4 threads, the time for 1000 runs increase to approx. 20 seconds.

![image](https://user-images.githubusercontent.com/688028/51523131-44e81c00-1e2b-11e9-8180-5f1a99221f38.png)

When upping to 8 threads (the number of logical processors, reported by `Environment.ProcessorCount`), I do manage to get the CPU utilization up to 100%, but 1000 runs now take 25-30 seconds, so about half the throughput.

Any ideas about why this happens? Why doesn't invoking Javascript in a loop saturate one CPU and leave the rest unaffected. Why does the throughput start dropping already at 4 threads even though I have 8 logical processors?

As a side note, in my real project which does non-trivial work (rendering of a React application) in the Javascript, the throughput drop is even more noticeable (20% when using 2 threads, 50% when using 4 threads).

I am using Microsoft.ClearScript version 5.5.4, .net framework 4.6.2

[ClearScriptSlowRepro.zip](https://github.com/Microsoft/ClearScript/files/2782016/ClearScriptSlowRepro.zip)

**Comment by ClearScriptLib** [comment]
Hi @erik-kallen,

> Why doesn't invoking Javascript in a loop saturate one CPU

We're using a different CPU, but in our tests with your program, running JavaScript code in _n_ threads _does_ saturate _n_ logical cores.

Here's a screenshot with `NumThreads` set to 1:

![image](https://user-images.githubusercontent.com/12966733/51555492-b2a14180-1e45-11e9-9807-5b8fe77ec6b8.png)

And here's one with `NumThreads` set to 8:

![image](https://user-images.githubusercontent.com/12966733/51555649-13c91500-1e46-11e9-876e-3545b0b7c778.png)

We can only guess why your results are different. Some possibilities might be virtual memory swapping or mobile CPU throttling.

> Why does the throughput start dropping already at 4 threads even though I have 8 logical processors?

While it executes script code, V8 does quite a bit of memory management work asynchronously, presumably to take advantage of multi-core and hyperthreaded processors. You can see in our screenshots that increasing the script thread count incurs growing load soaked up by additional logical cores.

Our theory is that this additional load begins affecting script execution as the script thread count approaches the _physical_ core count, since additional logical cores share at least some resources with the script threads.

Thanks!
